### ISSUE TITLE
Need schema validation for an object

### ISSUE THREAD

**Issue by dyetube** [NJsonSchema/NJsonSchema#111]
In my c# I have a `public object value { get; set; }` and in my json I have a key value pair where the key will always be a string but the value might be an integer, boolean or string so i cannot implicity set this as one of those three in the model.  I need it to be flexible.  For some reason the schema errors out with object expected.  How can i get around this?

**Comment by rsuter** [comment]
What have you tried so far? You can "or" the json schema type

**Comment by dyetube** [comment]
How do I "or" it?

**Comment by dyetube** [comment]
And just fyi, I have tried using a dynamic instead of an object still with no success.

**Comment by rsuter** [comment]
Are you using the JsonSchemaGenerator?

**Comment by dyetube** [comment]
No, here's my code:

`public JsonResult SubmitReport(string JsonStringSend, Guid ReportId, string UserReportFilename, string DocumentCategory, string DocumentReportingCategory, string DocumentDescription)
            {
dynamic JSend = JObject.Parse(JsonStringSend);
                var schema = JsonSchema4.FromType<ReportItem>();
                var schemaData = schema.ToJson();
                var errors = schema.Validate(JSend.JsonString);
}`

And here's my model(s):

`    public class ReportItem
    {

        [Required]
        public Guid ReportID { get; set; }

        [Required]
        public bool RequiresFilter { get; set; }

        [Required]
        public string MimeType { get; set; }

        [Required]
        public string ExternalID { get; set; }

        [Required]
        public string CreatedBy { get; set; }

        [Required]
        public string LastModified { get; set; }

        [Required]
        public string ExecutionScript { get; set; }

        [Required]
        public string ExecutionParameter { get; set; }

        public string ExecutionOrderBy { get; set; }

        public List<DynamicFilter> DynamicFilters { get; set; }

        public bool RequiresOrgID { get; set; }

        public QueryFilter ReportFilter { get; set; }

        public QueryRule ReportRules { get; set; }

        [Required]
        public List<QueryColumn> Columns { get; set; }
`

`    public class Rule
    {
        public string id { get; set; }
        public string @operator { get; set; }
        public object value { get; set; }
        public string condition { get; set; }
        public flags flags { get; set; }

    }
`

Does this help?

**Comment by rsuter** [comment]
Yes, a will fix that..

**Comment by dyetube** [comment]
Thanks Again!

**Comment by rsuter** [comment]
Thanks for using the library, will check and fix this tomorrow..

**Comment by dyetube** [comment]
Ok.  Thanks!

**Comment by rsuter** [comment]
Btw.: FromType internally uses JsonSchemaGenerator :-)

**Comment by rsuter** [comment]
Fyi see https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator

**Comment by dyetube** [comment]
I see that now!

**Comment by rsuter** [comment]
Please try again with v2.39

**Comment by rsuter** [comment]
Please reopen if not fixed

**Comment by rsuter** [comment]
Btw, object properties are now generated as empty schema, that means they are always valid...

**Comment by dyetube** [comment]
That works perfectly!  Thanks again!
