### ISSUE TITLE
NSwag: ResponseType WebAPI Annotation - List support C#

### ISSUE THREAD

**Issue by miccarlson** [NJsonSchema/NJsonSchema#112]
I have an endpoint which returns a list of objects in the HttpResponseMessage body. It would be nice to be able to set the ResponseType attribute to a List of objects, like in the snippet below.
`[ResponseType(List<object>)]`

Sorry, if I missed something when reading the docs, but I am not sure how to get around this issue.

**Comment by rsuter** [comment]
Is this an NSwag issue?

**Comment by rsuter** [comment]
Can you post some sample code and how you use NJsonSchema?

**Comment by miccarlson** [comment]
Here is an example endpoint which is modeled after something in our code.

```c#
[RoutePrefix("home")]
public class HomeController
{
    [Route("items")]
    [HttpGet]
    [ResponseType("200", typeof(List<Items>))]
    public HttpResponseMessage GetItems()
    {
            //This would return a list of items in the body of the response message
    }
}
```

As of now, I am not able to set the Response type property like in the code snippet above. I noticed that there is a class for observable dictionaries (Nswag.Collections.ObservableDictionary<>), but there is not one for List types.

I would rather not have to make a new model (i.e. ItemList) with a property of type List<Item> just for Swagger documentation to show that a list of Items is returned.

Thanks for helping me out with this!

**Comment by rsuter** [comment]
How does your response json look like (sample)? Have you tried ResponseType attribute as described here: https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator ?

**Comment by rsuter** [comment]
Your usage of ResponseType correctly describes the response as an array of Items... can you post the generated Swagger?

**Comment by rsuter** [comment]
Could you solve your problem?

**Comment by rsuter** [comment]
This is an nswag issue, please create an issue there if the problem remains
