### ISSUE TITLE
Support for handling different Property Name conventions

### ISSUE THREAD

**Issue by jkonecki** [NJsonSchema/NJsonSchema#115]
When using Json.NET `CamelCasePropertyNamesContractResolver` the serialized data has camel case property names. However NJsonSchema generates upper-case property names (based on reflection).

It would be beneficial to allow users to control the naming convention of the generated property names.

Suggested solution:
1. Define enum PropertyNameHandling { Default, CamelCase }
2. Add a new option `DefaultPropertyNameHandling` to `JsonSchemaGeneratorSettings`
3. Pass the naming convention to `Property.GetName()`

**Comment by jkonecki** [comment]
Should the Default `PropertyNameHandling` been actually called Reflection?

**Comment by rsuter** [comment]
CamelCasePropertyNamesContractResolver   inherits from DefaultContractResolver. So I think the DefaultContractResolver implements this reflection and thus Default would be ok?

**Comment by rsuter** [comment]
The question is whether CamelCasePropertyNamesContractResolver  applies ToCamelCase to the property name or also to the reflected name (respecting JsonProperty and DataMember attributes)

**Comment by jkonecki** [comment]
I'll double-check and write appropriate tests.

**Comment by rsuter** [comment]
Can we close this issue?

**Comment by jkonecki** [comment]
Yes. I'm happy with the implementation.
