### ISSUE TITLE
Incorrect handling of concrete IEnumerable types - they have "type:object", not "type:array"

### ISSUE THREAD

**Issue by RowlandBanks** [NJsonSchema/NJsonSchema#116]
Firstly, thankyou for building such an awesome tool :+1: 

I've just found a couple of edge-cases that it would be awesome if you could fix :)

Consider the following code:

```
public class ArrayModel<T> : IEnumerable<T>
{
    public IEnumerator<T> GetEnumerator() { return null; }
    
    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return this.GetEnumerator();
    }
}
<SNIP>
Console.WriteLine(JsonSchema4.FromType(typeof(ArrayModel<string>)).ToJson());
```

This will print the correct JSON schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "string"
  }
}
```

However, there are a couple of ways we can change this that *won't* generate the correct schema:

## BROKEN 1
If we make the type of the IEnumerable concrete

```
public class ArrayModel : IEnumerable<string>
{
    public IEnumerator<string> GetEnumerator() { return null; }
    
    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return this.GetEnumerator();
    }
}
<SNIP>
Console.WriteLine(JsonSchema4.FromType(typeof(ArrayModel)).ToJson());
```
we find it doesn't print the type of the array items

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {} // Missing type in here.
}
```

## BROKEN 2

Inheriting from a concrete type like List
```
public class ArrayModel<T> : List<T>
{
}
<SNIP>
Console.WriteLine(JsonSchema4.FromType(typeof(ArrayModel<string>)).ToJson());
```
produces
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object", // It is treating this as an object, not an array. 
                             // Note that generating from List<string> works correctly.
  "x-typeName": "ArrayModelString",
  "additionalProperties": false,
  "allOf": [
    {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  ]
}
```

**Comment by rsuter** [comment]
Ok, in v2.41 you can add the JsonSchemaAttribute and manually define the item type: 

    [JsonSchema(JsonObjectType.Array, ArrayItem = typeof(string))]
    public class ArrayModel : IEnumerable<string>
    {
        public IEnumerator<string> GetEnumerator() { return null; }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

this should solve both your problems

**Comment by RowlandBanks** [comment]
Thanks @rsuter - that will work absolutely fine for me :+1:
