### ISSUE TITLE
Do not generate optional properties in TypeScript

### ISSUE THREAD

**Issue by rsuter** [NJsonSchema/NJsonSchema#119]
Is it ok if I remove all `?` on the generated interface properties? We just had a bug, where the interface was: 

```
interface Person {
     parents: Person[];
}
```

And someone forgot the "s" postfix:

```
var x = <Person>{
    parent: { ... }
}
```

Which didn't yield a compiler error because the `parents` property is optional...
This is why I want to completely avoid `?` (all TS properties are nullable anyways).

What do you think?

**Comment by MaartenThomassen** [comment]
Perhaps that would be a good idea. There is another option though.

If you use json.net, you can add the JsonPropertyAttribute to a property with the Required property to Required.Always (see http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonPropertyAttribute_Required.htm).

This will remove the?  during code generation.

**Comment by rsuter** [comment]
Yes, using JsonPropertyAttribute.Required or the RequiredAttribute removes the ?. But the semantics of ? is not nullability but optionality which cannot be expressed in a TS interface... or better not-nullability cannot be expressed... The problem is, that there must be lots of required attributes just to have safer TS...

**Comment by MaartenThomassen** [comment]
I agree using the attribute introduces alot of bloat. The eaay solution would be to remove the optionality for the generated interfaces.

The semantics of an interface are that a class should mimimally implement its defined members,  if they are all optional then you could wonder why use an interface anyway.

So yes, perhaps removing them is best.

**Comment by rsuter** [comment]
Discussion here: https://gitter.im/NSwag/NSwag

**Comment by simeyla** [comment]
What are you talking about 'all TS properties are nullable anyways'. 
The ? in typescript isn't really about whether it is nullable - it is about whether it is required.

> Optional Properties
> Not all properties of an interface may be required. Some exist under certain conditions or may not be there at all. These optional properties are popular when creating patterns like “option bags” where you pass an object to a function that only has a couple of properties filled in.
https://www.typescriptlang.org/docs/handbook/interfaces.html

I am trying to use NSwagStudio to generate interfaces. For instance this is a simple interface that represents search criteria:

export interface SearchOrdersCriteria {
    maxOrders?: number;
    orderID: string;
    username: string;
}

I want maxOrders to be optional when calling my client but it isn't being generated.

I agree that an interface in general should be to minimally implement its defined members, but I just want a strongly named / typed way to call my service with optional parameters. Typescript doesn't really treat interfaces like this so I think this change is a big mistake.

Why can't this be an option that I choose with for instance something like :

        [JsonProperty("maxOrders", Required = Required.AllowNull)]
