### ISSUE TITLE
.NET 4.0 Support

### ISSUE THREAD

**Issue by slow-loris** [NJsonSchema/NJsonSchema#130]
Hi all,

I want to use the library for a project running on .NET 4.0 and we are using VS 2010.
Is there any possibility to use the library under this circumstances?

**Comment by rsuter** [comment]
The PCL 259 doesnt work, right?

**Comment by slow-loris** [comment]
No. If I want to install the nuget package, this error occurs:
<pre>
PM> Install-Package NJsonSchema
Attempting to resolve dependency 'Newtonsoft.Json (≥ 8.0.3)'.
Installing 'NJsonSchema 2.48.6012.40848'.
Successfully installed 'NJsonSchema 2.48.6012.40848'.
Adding 'NJsonSchema 2.48.6012.40848' to json_test.
Uninstalling 'NJsonSchema 2.48.6012.40848'.
Successfully uninstalled 'NJsonSchema 2.48.6012.40848'.
Install failed. Rolling back...
Install-Package : Could not install package 'NJsonSchema 2.48.6012.40848'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package d
oes not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  NJsonSchema
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 </pre>

**Comment by rsuter** [comment]
I have to check whether it's possible to implement a .net 4 supporting pcl...

**Comment by rsuter** [comment]
You only need the core lib?

**Comment by slow-loris** [comment]
Yes the core lib would be enough for me.

**Comment by rsuter** [comment]
Its more complicated than i thought... some important classes are missing in the .net 4 pcl profile...

**Comment by rsuter** [comment]
First working version: https://github.com/NJsonSchema/NJsonSchema/tree/Net4Support

Please clone and build project and test it within your solution

**Comment by rsuter** [comment]
Do you still need this? Or did you find an alternative? The .net 4 project is called NJsonSchema.Net4

**Comment by rsuter** [comment]
Added .NET 4 support in v2.64

**Comment by rsuter** [comment]
Needs a different package => soon.

**Comment by rsuter** [comment]
Fixed in v4.0
