### ISSUE TITLE
Support Newtonsoft.Json.JsonProperty [Required] field

### ISSUE THREAD

**Issue by acelot** [NJsonSchema/NJsonSchema#14]
Such as `Required`, `PropertyName`, `NullValueHandling`. I don't know how to use other properties.

**Comment by rsuter** [comment]
PropertyName is already suppoerted...

**Comment by rsuter** [comment]
Support for Required makes sense...

**Comment by rsuter** [comment]
I think NullValueHandling is not relevant for the schema..

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/143ade60c301a180dce184c2d35637e546015216
