### ISSUE TITLE
Add CustomAttribute

### ISSUE THREAD

**Issue by breslavsky** [NJsonSchema/NJsonSchema#145]
Please add custom attributes please.

```
[Custom(Name = "Size", Value = "100px")]
public string Title { get; set; }
```

JSON Schema:

```
"properties": {
        "title": {
            "type": ["null", "string"],
            "size": "100px"
        }
```

Thanks!

**Comment by rsuter** [comment]
You can use the JsonSchemaExtensionDataAttribute: https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/Annotations/JsonSchemaExtensionDataAttribute.cs

Each attribute is added as attribute with the prefix "x-" (custom attributes allowed by JSON Schema)

**Comment by breslavsky** [comment]
Good. How can I add multiple JsonSchemaExtensionData?

**Comment by rsuter** [comment]
Do you get a compiler error when you use multiple attributes?

**Comment by breslavsky** [comment]
Yes. 
CS0579	Duplicate 'JsonSchemaExtensionData'


        [Display(Name = "Identificatio")]
        [JsonSchemaExtensionData("x-size", "flex-2")]
        [JsonSchemaExtensionData("x-hidden", "1")]
        public Guid Id { get; set; }

**Comment by rsuter** [comment]
Yes, thats a bug, will fix it today..

**Comment by breslavsky** [comment]
Thank you! Very nice job. Publish please new version on NuGet.

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/2445f2d14cfcf8cde61fd0b27af704eb73a41461

**Comment by rsuter** [comment]
New version available

**Comment by rsuter** [comment]
Added documentation: https://github.com/NJsonSchema/NJsonSchema/wiki/Custom-Schema-Properties
