### ISSUE TITLE
ipv4 validation error

### ISSUE THREAD

**Issue by tokenoverlord** [NJsonSchema/NJsonSchema#151]
The regex used to validate ipv4 address will give an error if the most significant byte is 2x6 to 2x9 with "x" being digits from 0 to 9.

For example 209.88.45.105 will give an error.

The regex is located in [JsonSchemaValidator.cs](https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/Validation/JsonSchemaValidator.cs) lines 193 to 195.

**Comment by rsuter** [comment]
Can you propose a correct regex?

**Comment by tokenoverlord** [comment]
Currently looking at "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$".

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/9cf5d0bb5bfc928a0986b75dac7d389f2083db81

**Comment by rsuter** [comment]
Try v2.60
