### ISSUE TITLE
'Required' is not an attribute class

### ISSUE THREAD

**Issue by juanpmarin-infocorp** [NJsonSchema/NJsonSchema#154]
Hi, when I generate from Json Schema the generated code uses [Required]

![screenshot_16](https://cloud.githubusercontent.com/assets/13415603/16962147/0d166dce-4db6-11e6-92f6-b3601eb55f96.png)

**Comment by rsuter** [comment]
What .NET platform do you use?

**Comment by juanpmarin-infocorp** [comment]
4.5

**Comment by rsuter** [comment]
You need to add the `System.ComponentModel.DataAnnotations` assembly reference to your project...

**Comment by juanpmarin-infocorp** [comment]
It works, thanks :D
