### ISSUE TITLE
Ignored type of pattern properties

### ISSUE THREAD

**Issue by juanpmarin-infocorp** [NJsonSchema/NJsonSchema#157]
Hi
When I specify something like:
```
"patternProperties": {
  "[a-zA-Z_$][a-zA-Z_$0-9]*": {
    "type": "string"
  }
}
```
The resultant code is:
`  Dictionary<string, object>`
Instead of
`  Dictionary<string, string>`

**Comment by rsuter** [comment]
Is this unit test fine for you?

	[TestMethod]
	public void When_patternProperties_is_set_with_string_value_type_then_correct_dictionary_is_generated()
	{
		//// Arrange
		var schemaJson = @"{
			""properties"": {
				""dict"": {
					""type"": ""object"", 
					""patternProperties"": {
					  ""[a-zA-Z_$][a-zA-Z_$0-9]*"": {
						""type"": ""string""
					  }
					}
				}
			}
		}";

		var schema = JsonSchema4.FromJson(schemaJson);

		//// Act
		var generator = new CSharpGenerator(schema, new CSharpGeneratorSettings { ClassStyle = CSharpClassStyle.Poco });
		var code = generator.GenerateFile();

		//// Assert
		Assert.IsTrue(code.Contains("public Dictionary<string, string> Dict { get; set; }"));
	}

**Comment by rsuter** [comment]
Commit: https://github.com/NJsonSchema/NJsonSchema/commit/33160aa1934df84f7f085edc926326672e25d7fd

**Comment by rsuter** [comment]
If you confirm that this is the expected behavior, then I'll create a new NuGet release..

**Comment by juanpmarin-infocorp** [comment]
I think that the type of the patternProperties can only be taken when the additionalProperties are disabled
The schema shold be:
```
 "properties": {
     "dict": {
         "type": "object",
         "additionalProperties": false,
         "patternProperties": {
             "^[a-zA-Z_$][a-zA-Z_$0-9]*$": {
                 "type": "string"
             }
         }
     }
 }
```

I suggest improve the regex:
`^[a-zA-Z_$][a-zA-Z_$0-9]*$`

**Comment by rsuter** [comment]
I think this should be fine: 

    protected string ResolveDictionaryValueType(JsonSchema4 schema, string fallbackType)
    {
        if (schema.AdditionalPropertiesSchema != null)
            return Resolve(schema.AdditionalPropertiesSchema, false, null);

        if (schema.AllowAdditionalItems == false && schema.PatternProperties.Count == 1)
            return Resolve(schema.PatternProperties.First().Value, false, null);

        return fallbackType;
    }

If one patternProperties is defined, then its schema is used as dictionary value type (otherwise "object").

**Comment by juanpmarin-infocorp** [comment]
That would not work well if declared several patternProperties of different types, for example: 
```
 "properties": {
     "dict": {
         "type": "object",
         "additionalProperties": false,
         "patternProperties": {
             "^[a-zA-Z_$][a-zA-Z_$0-9]*$": {
                 "type": "string"
             },
             "^[0-9]*$": {
                 "type": "integer"
             }
         }
     }
 }
```

I think they should be compared to determine the type, and if they are not all equal then use "object"

**Comment by rsuter** [comment]
Ok, now: 

    protected string ResolveDictionaryValueType(JsonSchema4 schema, string fallbackType)
    {
        if (schema.AdditionalPropertiesSchema != null)
            return Resolve(schema.AdditionalPropertiesSchema, false, null);

        if (schema.AllowAdditionalProperties == false && schema.PatternProperties.Any())
        {
            var valueTypes = schema.PatternProperties
                .Select(p => Resolve(p.Value.ActualSchema, false, null))
                .Distinct()
                .ToList();

            if (valueTypes.Count == 1)
                return valueTypes.First();
        }

        return fallbackType;
    }

**Comment by juanpmarin-infocorp** [comment]
Yeah :D

**Comment by rsuter** [comment]
v2.62 build/deployment running: https://ci.appveyor.com/project/rsuter/njsonschema
