### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by fleed** [NJsonSchema/NJsonSchema#159]
any plan to support .net core?

**Comment by rsuter** [comment]
.NET core is supported (via .NET standard 1.6)

**Comment by rsuter** [comment]
Do you have problems installing or using it in .net core?

**Comment by fleed** [comment]
I haven't seen it mentioned anywhere. I will give it a try.
In the meanwhile, I can close this issue.

**Comment by rsuter** [comment]
Added to readme

**Comment by rsuter** [comment]
The xml doc reader requires additional packages: https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation

**Comment by fleed** [comment]
Thank you very much, I really appreciate the quick support.

I'm planning to use it in a [loopback.io](https://loopback.io)-like project I'm developing ([swan](https://github.com/fleed/swan)), but being able to run it on all platforms is for me a string requirement.

**Comment by rsuter** [comment]
Yes, this is also a requirement for my projects... If you have any problems please contact me again.

**Comment by rsuter** [comment]
You should also check NJsonSchema's sister project NSwag: http://nswag.org
