### ISSUE TITLE
How to set multipleOf via data attribute?

### ISSUE THREAD

**Issue by acelot** [NJsonSchema/NJsonSchema#16]

**Comment by rsuter** [comment]
Not possible atm... How should this look like?

**Comment by acelot** [comment]
Usually, `multipleOf` used with range attribute. So we can extend Range attribute and add `MultipleOf` property.

**Comment by rsuter** [comment]
Ah, I thought, this is used as some sort of inheritance; but it is used for numbers: 
http://spacetelescope.github.io/understanding-json-schema/reference/numeric.html?highlight=multipleof
Is there an existing attribute we can use (e.g. a property on Range), or where should this new attribute be implemented? A new NuGet package like in NSwag (https://www.nuget.org/packages?q=NSwag)?

**Comment by rsuter** [comment]
Added in commit https://github.com/NJsonSchema/NJsonSchema/commit/996310ae593dc5decf3d31f47e6330c25aa2d483
