### ISSUE TITLE
Getting rid of System.Runtime 

### ISSUE THREAD

**Issue by tebeco** [NJsonSchema/NJsonSchema#170]
Is there a way to get rid of "System.Runtime" or is it mandatory ?
I mean, in VS2015 it cause a lot of hell if you google :
System.Object not found reference System.Runtime

Or is it possible to "enrich" the nuget to Target .net 451 / 452 / 46x with "linked file" ?
(Instead of a "target the world PCL" ?)

I'm not saying it's a bad choice, but something is going mad around that.
We've installed vs2015 on win7 at works depending on VS2015 installation we do not have this assembly :(
Especially the templates Xamarin UWP UAP Xamarin etc .. "may" install it's not really clear

**Comment by rsuter** [comment]
I don't have any problems with the PCL in VS2015, and it is not planned to add more DLLs because it always makes the project more complicated. Do you actually have any problems?

**Comment by tebeco** [comment]
Well vs2015 dosent find System.Runtime wich is added when installing this nuget
It build and run locally if we remove System.Runtime
And on build agent it says that System.object cannot be found and ask us to reference System.Runtime

So i'm wondering does comes from System.Runtime and if it's needed

**Comment by rsuter** [comment]
What is the target .net framework?

**Comment by tebeco** [comment]
Arg ... Mobility lost my post
Net451 and in a really near future net461 or 462

**Comment by tebeco** [comment]
Vs2013 seems ok whereas vs2015 is not even if the Facades exists in programfilesX86

**Comment by rsuter** [comment]
Do you use the latest vs2015 update 3 with all patches. I think there was a problem with one vs2015 update and pcls..

**Comment by tebeco** [comment]
Yep everything is updated to latest bits
And same goes on multiple computers

**Comment by rsuter** [comment]
I have to try this myself, but it should work without problems... Maybe the latest release broke it...

**Comment by rsuter** [comment]
In my sample project it works without problems, can you attach a simple sample project where I can reproduce the problem?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/a5b2b9365272d5fecefb86517997c58fdf144420

**Comment by rsuter** [comment]
Depending on your target framework, you still need to manually add the "Microsoft.NETCore.Portable.Compatibility" package...

**Comment by rsuter** [comment]
I removed the dependency because it caused problems in non core projects, add the compat. package manually

**Comment by rsuter** [comment]
For now ill leave it as is because maintainig a lib for all targets is a big effort...

**Comment by tebeco** [comment]
;)
I'll push the word
