### ISSUE TITLE
additionalProperties (object) fails to validate

### ISSUE THREAD

**Issue by thunder7553** [NJsonSchema/NJsonSchema#173]
Hello!

I am using NSwag to model a swagger.json that is valid for CouchDB - and it seems to me, that the validation of attachments does not work correctly. 

``` json
{
  "id": "https://localhost/array",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "couchDoc": { "$ref": "#/definitions/CouchDBDoc" }
  },
  "definitions": {
    "CouchDBDoc": {
      "properties": {
        "_id": {
          "type": "string"
        },
        "_rev": {
          "type": "string"
        },
        "_attachments": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "content_type": {
                "type": "string"
              },
              "revpos": {
                "type": "string"
              },
              "digest": {
                "type": "string"
              },
              "length": {
                "type": "integer",
                "format": "int32"
              },
              "stub": {
                "type": "boolean"
              }
            }
          }
        }
      },
      "type": "object"
    }
  }
}
```

And the json fragment:
``` json
{
  "couchDoc": {
    "_id": "a8efd3c91985279c8f4882e14f33551e",
    "_rev": "1-d1ec00873703cc1e6a41554de2eebe77",
    "_attachments": {
      "image": {
        "content_type": "application/octet-stream",
        "revpos": 1,
        "digest": "md5-l7ZIe3+wrfBKB5qROXH3hw==",
        "length": 236694,
        "stub": true
      }
    }
  }
}
```

I made a small standalone schema and a unit test for it. 

[UnitTestProject1.zip](https://github.com/NJsonSchema/NJsonSchema/files/413109/UnitTestProject1.zip)

**Comment by rsuter** [comment]
I serialized the validation result: 

`
[
  {
    "Errors": {
      "NJsonSchema.JsonSchema4": [
        {
          "Kind": 1,
          "Property": "revpos",
          "Path": "#/couchDoc._attachments.image.revpos"
        }
      ]
    },
    "Kind": 35,
    "Property": "image",
    "Path": "#/couchDoc._attachments.image"
  }
]
`

As you can see, you defined `revpos` as string but in the test data, the property is an integer....

With 

    "revpos": {
        "type": "integer"
    },

your unit tests is green..

**Comment by thunder7553** [comment]
(facepalm) stupid me. Sorry.

**Comment by rsuter** [comment]
No problem. Thanks for using the library.
