### ISSUE TITLE
Consider using the Apache 2.0 license

### ISSUE THREAD

**Issue by ohadschn** [NJsonSchema/NJsonSchema#178]
Any reason for the MS-PL license? It's a bit harder to understand and make sure you're compliant with than similar alternatives. For example: http://programmers.stackexchange.com/questions/85301/understanding-the-microsoft-public-license-ms-pl. 

Apache 2.0 is one of those licenses you know you can just use basically however you want without worrying about it too much, and as far as I understand it protects the authors just as well.

**Comment by rsuter** [comment]
I'm thinking about switching to an MIT license..

**Comment by ohadschn** [comment]
Even better!
