### ISSUE TITLE
JsonSchema4 cannot load Azure ARM template schema.

### ISSUE THREAD

**Issue by windoze** [NJsonSchema/NJsonSchema#179]
`var schema = JsonSchema4.FromUrl("https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json");`

This statement hung for hours and memory usage kept increasing, not sure what happened.

**Comment by rsuter** [comment]
Loading now works: https://github.com/NJsonSchema/NJsonSchema/commit/c20e0d0fa1f8ffffc7a87492b51f3e38e2e64b7e

But im not sure if it validates correctly...

**Comment by rsuter** [comment]
Try again with v4.2
