### ISSUE TITLE
Add support for Data Annotation subclasses

### ISSUE THREAD

**Issue by DorianGreen** [NJsonSchema/NJsonSchema#189]
By changing the TryGetAttribute method to this:

```
private Attribute TryGetAttribute(IEnumerable<Attribute> attributes, string attributeType)
{
       return attributes.FirstOrDefault(a => Type.GetType(attributeType, false, true).IsInstanceOfType(a));
}
```

or:

```
private Attribute TryGetAttribute(IEnumerable<Attribute> attributes, string attributeType)
{
       return attributes.FirstOrDefault(a => a.GetType().InheritsFrom(attributeType));
}
```
From: https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/Infrastructure/ReflectionExtensions.cs

we can support any subclass of the Data Annotation attributes.
E.g., we can get Email and Phone for free if we check for the base DataTypeAttribute.

This feature is also useful for custom validation attributes that inherit from the base Data Annotations ones.

A note on InheritsFrom:
It seems like the method will only check inheritance, so comparing DataType against itself will fail.

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/baaa6a3afd2f2e632ad2ca2cd1a2dd4edc509d34

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/baaa6a3afd2f2e632ad2ca2cd1a2dd4edc509d34
