### ISSUE TITLE
LoadEnumerations throws an exception when an enum inherits from byte

### ISSUE THREAD

**Issue by MaartenThomassen** [NJsonSchema/NJsonSchema#19]
When an enum which inherits from byte is loaded, the code throws and exeption.

Example: 

```
public enum PermissionFlags : byte
    {
        Create  = 0x01,
        Read    = 0x02,
        Update  = 0x04,
        Delete  = 0x08,
    }
```
The exception occurs in NJsonSchema (line 248 of JsonScheamGenerator.cs)

```var value = (int) Enum.Parse(type, enumName);```

"Specified cast is not valid" is the exception

**Comment by rsuter** [comment]
I will fix this today..

**Comment by rsuter** [comment]
Fixed in v1.26

**Comment by MaartenThomassen** [comment]
Much apreciated

**Comment by rsuter** [comment]
Is it working for you?

**Comment by MaartenThomassen** [comment]
I just updated my packages and my unit tests are passing now so it looks like its working.
