### ISSUE TITLE
Generating C# from Json Schema results in 'Anonymous' classes

### ISSUE THREAD

**Issue by josephcooney** [NJsonSchema/NJsonSchema#199]
Hi

When I use the CSharpGenerator with CSharpClassStyle.Poco passing in the JSON schema created by parsing the Person JSON schema from README [1] I get two types named Anonymous and Anonymous1 in the generated output [2]. I think Anonymous should be named 'Person' and Anonymous1 should be 'Car'. Does this seem like an issue or am I doing something wrong? I am using nuget package version 4.12.6103.41722 of NJsonSchema.CodeGeneration and version 4.12.6103.41721 of NJsonSchema.

If you believe it is an issue I'd be happy to work on a fix. 

[1] Person JSON schema from README
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "typeName": "Person",
  "additionalProperties": false,
  "required": [
    "FirstName",
    "LastName"
  ],
  "properties": {
    "FirstName": {
      "type": "string"
    },
    "MiddleName": {
      "type": [
        "null",
        "string"
      ]
    },
    "LastName": {
      "type": "string"
    },
    "Gender": {
      "oneOf": [
        {
          "$ref": "#/definitions/Gender"
        }
      ]
    },
    "NumberWithRange": {
      "type": "integer",
      "maximum": 5.0,
      "minimum": 2.0
    },
    "Birthday": {
      "type": "string",
      "format": "date-time"
    },
    "Company": {
      "oneOf": [
        {
          "$ref": "#/definitions/Company"
        },
        {
          "type": "null"
        }
      ]
    },
    "Cars": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "typeName": "Car",
        "additionalProperties": false,
        "properties": {
          "Name": {
            "type": [
              "null",
              "string"
            ]
          },
          "Manufacturer": {
            "oneOf": [
              {
                "$ref": "#/definitions/Company"
              },
              {
                "type": "null"
              }
            ]
          }
        }
      }
    }
  },
  "definitions": {
    "Gender": {
      "type": "integer",
      "typeName": "Gender",
      "enumNames": [
        "Male",
        "Female"
      ],
      "enum": [
        0,
        1
      ]
    },
    "Company": {
      "type": "object",
      "typeName": "Company",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": [
            "null",
            "string"
          ]
        }
      }
    }
  }
}`

[2] Generated Output
`
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v4.12.6103.41721 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Specialized;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.CompilerServices;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Foo.Bar
{
    #pragma warning disable // Disable all warnings

    [JsonObject(MemberSerialization.OptIn)]
    [GeneratedCode("NJsonSchema", "4.12.6103.41721")]
    public partial class Anonymous 
    {
    
        [JsonProperty("FirstName", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }
    
        [JsonProperty("MiddleName", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string MiddleName { get; set; }
    
        [JsonProperty("LastName", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }
    
        [JsonProperty("Gender", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public Gender Gender { get; set; }
    
        [JsonProperty("NumberWithRange", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public int NumberWithRange { get; set; }
    
        [JsonProperty("Birthday", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public DateTime Birthday { get; set; }
    
        [JsonProperty("Company", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public Company Company { get; set; }
    
        [JsonProperty("Cars", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public ObservableCollection<Anonymous1> Cars { get; set; }
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static Anonymous FromJson(string data)
        {
            return JsonConvert.DeserializeObject<Anonymous>(data);
        }
    }
    
    [GeneratedCode("NJsonSchema", "4.12.6103.41721")]
    public enum Gender
    {
        _0 = 0,
    
        _1 = 1,
    
    }
    
    [JsonObject(MemberSerialization.OptIn)]
    [GeneratedCode("NJsonSchema", "4.12.6103.41721")]
    public partial class Company 
    {
    
        [JsonProperty("Name", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static Company FromJson(string data)
        {
            return JsonConvert.DeserializeObject<Company>(data);
        }
    }
    
    [JsonObject(MemberSerialization.OptIn)]
    [GeneratedCode("NJsonSchema", "4.12.6103.41721")]
    public partial class Anonymous1 
    {
    
        [JsonProperty("Name", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    
        [JsonProperty("Manufacturer", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public Company Manufacturer { get; set; }
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static Anonymous1 FromJson(string data)
        {
            return JsonConvert.DeserializeObject<Anonymous1>(data);
        }
    }
}
`

**Comment by josephcooney** [comment]
Ooops, a bit more reading and I can see this can be done by ITypeNameGenerator

**Comment by rsuter** [comment]
The generator tries to infer the type name for a schema but the fallback is anonymous. You can set the type name with the "x-typeName" property... (Set this property on the root schema)

**Comment by rsuter** [comment]
Btw: the schema in the readme is outdated/wrong: just replace all "typeName" properties with "x-typeName"
