### ISSUE TITLE
Not able to use JsonSchema4.FromType on UWP

### ISSUE THREAD

**Issue by wleev** [NJsonSchema/NJsonSchema#20]
The static initialization of `XpathExtensionsType` in `FullDotNetMethods` throws a `TypeInitializationException` when used in a UWP app. This can be solved using a static constructor and a try/catch, but I wanted to make sure if this is reproducible and I'm not missing anything.

Thanks.

**Comment by rsuter** [comment]
I will fix this today..

**Comment by wleev** [comment]
Great! Thanks for the speedy reply.

**Comment by rsuter** [comment]
Fixed in v1.26
