### ISSUE TITLE
JsonInheritanceConverter thread safety

### ISSUE THREAD

**Issue by neotek** [NJsonSchema/NJsonSchema#206]
Hi

Thanks for providing such a nice Swagger/JsonSchema implementation including discriminator support.
I tried to implemented this in a Project. Unfortunately the JsonInheritanceConverter seems not to be thread safe. In Unit Tests I get random exceptions as the discriminator field is not present in the written Json.
Setting the contract.Converter = null; in WriteJson() seems to cause that issue.

Has anyone solved this?

Thanks
Urs

**Comment by rsuter** [comment]
This is bad, I could not find another way to implement this...

**Comment by rsuter** [comment]
We need a fix for that. There are unit tests to check its functionality, so it should be simple to experiment...

**Comment by rsuter** [comment]
Why is this running in parallel?

**Comment by rsuter** [comment]
Is the serializer reused?

**Comment by neotek** [comment]
It runs in parallel as it speeds up unit and integration tests. But this could happen in other parallel scenarios as well.
I'm using it like this: JsonConvert.SerializeObject(entity, Newtonsoft.Json.Formatting.Indented, GetJsonSerializerSettings())
So the JsonSerializerSettings are not reused.

**Comment by rsuter** [comment]
So if you call JsonConvert.SerializeObject then you see these problems? I thought that SerializeObject creates a new serializer to prevent these problems... But it seems that it reuses the serializer internally... 

My problem: I could not find a way to implement the converter without setting the Converter to null...

**Comment by rsuter** [comment]
I think this is the problem:

http://stackoverflow.com/questions/33557737/does-json-net-cache-types-serialization-information

But creating a new resolver each time is not an option because it would degrade the performance dramatically...

**Comment by rsuter** [comment]
Ill try something with thread local... But i have to find a solution to reproduce your problem in a unit test first...

**Comment by neotek** [comment]
I see. Yes, I also was not able to find a solution that works.
This implementation seems to have the same Problem:
https://github.com/Azure/autorest/blob/45ddc1a84c58f5732a2f77418079c9439f39e892/src/client/Microsoft.Rest.ClientRuntime/Serialization/PolymorphicSerializeJsonConverter.cs

I tried to implement a workaround by defining a property on the base class with the name of the discriminator:

        [JsonProperty]
        public string Kind
        {
            get
            {
                if (string.IsNullOrEmpty(_kind))
                {
                    Type type = this.GetType().UnderlyingSystemType;
                    _kind = type.Name;

                    return type.Name;
                }

                return _kind;
            }
        }

This works for Serialize/Deserialize the data, but when i try to build the swagger.json I get an exception as the field is defined multiple times.
https://github.com/NJsonSchema/NJsonSchema/blob/baaa6a3afd2f2e632ad2ca2cd1a2dd4edc509d34/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L304

Thanks for your help.

**Comment by rsuter** [comment]
The "defined multiple times" can easily be fixed... 
But I don't like that you have to implement the property yourself...

**Comment by rsuter** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/386

**Comment by rsuter** [comment]
I think I have found a solution...

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/62850de78f55a3ffdc42c0006cee92f58c37d5aa

**Comment by rsuter** [comment]
Also updated in NSwag: https://github.com/NSwag/NSwag/commit/a47fca71901021d3747eac5980f29a27c4713be4

**Comment by rsuter** [comment]
Check out v4.18

**Comment by neotek** [comment]
Hey, thank you.
For me this solution still does not work as I use nested structures with additional classes that have discriminators.

I extended the Tests here:
https://github.com/neotek/NJsonSchema/commit/6246910f651da348d34d989be33af13feaa880ac

With the new approach all child elements are deserialized to the base class. The JsonInheritanceConverter seems to gets called recursively and is disabled on the child elements.

**Comment by rsuter** [comment]
Ok, next workaround :-), now it should work as expected: 

https://github.com/NJsonSchema/NJsonSchema/commit/97228f2baed6ceb0ed98af6686fdbd8faada0e49

**Comment by rsuter** [comment]
v4.19

**Comment by neotek** [comment]
That helped.
No failing unit tests anymore.
Thanks a lot.
