### ISSUE TITLE
Feature suggestion: Support for [DataMember(IsRequired = true)]

### ISSUE THREAD

**Issue by timovi** [NJsonSchema/NJsonSchema#214]
Would it be possible to support System.Runtime.Serialization.DataMemberAttribute's IsRequired-property in schema generation?

**Comment by rsuter** [comment]
Is this IsRequired property also respected by the Json.NET (Newtonsoft.Json) serializer?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/626c1cecb00d7c2a3abb7bfefd950ef52086f96e
