### ISSUE TITLE
Class with enum produces incorrect SchemaReferencePath

### ISSUE THREAD

**Issue by cpx** [NJsonSchema/NJsonSchema#216]
Given this generator setup and API controller:
```csharp
class Program
{
    static void Main(string[] args)
    {
        var genSettings = new WebApiAssemblyToSwaggerGeneratorSettings();
        genSettings.AssemblyPaths = new[]
        {
            typeof(FooController).Assembly.Location,
        };
        genSettings.DefaultUrlTemplate = "api/{controller}/{action}/{id}";
        genSettings.DefaultEnumHandling = EnumHandling.String;
        genSettings.DefaultPropertyNameHandling = PropertyNameHandling.Default;
        genSettings.NullHandling = NullHandling.Swagger;
        var gen = new WebApiAssemblyToSwaggerGenerator(genSettings);
        var service = gen.GenerateForControllers(gen.GetControllerClasses());
    }
}

public class FooController : ApiController
{
    [Route("foos/")]
    public Foo[] GetFoos([FromUri] Bar[] bars)
    {
        return new Foo[0];
    }
}

public enum Bar
{
    Baz,
    Foo
}

public class Foo
{
    public Bar Bar { get; set; }
}
```

This causes NJsonSchema.JsonReferenceResolver to throw InvalidOperationException ""Could not resolve the path '#/paths//foos/Get/parameters/0/schema'."

I haven't figured out exactly how this value gets produced, but inspecting the root SwaggerService object:
```this.Definitions["Foo"].Properties["Bar"].SchemaReferencePath``` is equal to #/paths//foos/Get/parameters/0/schema

If you remove either the Bar property from Foo, or the Bar[] parameter from GetFoos() the exception goes away. It seems to be the combination that produces the result.

**Comment by rsuter** [comment]
Fixed https://github.com/NSwag/NSwag/commit/09c6406e7669ffa3cd855d5d2ab376b1b2a0cdf4

**Comment by rsuter** [comment]
Please retry with latest CI build (NSwag)

**Comment by cpx** [comment]
Yup, seems to work. Any plans to publish it to NuGet soon? :)

**Comment by rsuter** [comment]
The updated NSwag binaries?

**Comment by cpx** [comment]
Yes, exactly. I'm trying to get NSwag into a CI build so compiling it myself is a bit of a hassle.

**Comment by rsuter** [comment]
v6.6 released

**Comment by cpx** [comment]
Thanks! :)
