### ISSUE TITLE
Schema generation issue for cascaded type in NJsonSchema.Net4

### ISSUE THREAD

**Issue by TekkBob** [NJsonSchema/NJsonSchema#218]
Given this simple hierarchy:
```csharp
public class Root
{
	[Required]
	public Node SubNode { get; set; }
}

public class Node
{
	[Required]
	public string Leaf { get; set; }
}

private static void BuildSchema()
{
	var schema = JsonSchema4.FromType<Root>();
	var schemaData = schema.ToJson();
}
```

the generated schema lacks the definition of 'Node' type

```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Root",
  "additionalProperties": false,
  "required": [
    "SubNode"
  ],
  "properties": {
    "SubNode": {
      "oneOf": [
        {}
      ]
    }
  }
}
```

**Comment by rsuter** [comment]
And this works with the non-legacy DLL (ie with .NET 4.5+)?

**Comment by TekkBob** [comment]
yes, the schema output of the non-legacy project is
```JavaScript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "x-typeName": "Root",
  "additionalProperties": false,
  "required": [
    "SubNode"
  ],
  "properties": {
    "SubNode": {
      "oneOf": [
        {
          "$ref": "#/definitions/Node"
        }
      ]
    }
  },
  "definitions": {
    "Node": {
      "type": "object",
      "x-typeName": "Node",
      "additionalProperties": false,
      "required": [
        "Leaf"
      ],
      "properties": {
        "Leaf": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by TekkBob** [comment]
I think I found a solution. Hope it doesn't break something else!
In legacy part of ReflectionChache.GetProperties adding additional binding flags solves the problem for me:

```csharp
var declaredProperties = type.GetTypeInfo().GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
var declaredFields = type.GetTypeInfo().GetFields(BindingFlags.Public | BindingFlags.Instance);
```

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/0ab7b3c228d29997bcd0b0670d74078616304cc4

but it does not fix all unit tests

**Comment by TekkBob** [comment]
It seems to fix all but 2 unit tests, which might have unrelated reasons. Without the BindingFlags-change almost all tests fail.

**Comment by rsuter** [comment]
Yes. But these 2 unit tests also have a problem with reflection somewhere...
Try Release v4.27

**Comment by TekkBob** [comment]
Yes, the MinLengthAttribute and MaxLengthAttribute aren't defined in .NET 4.0.
(not sure why it compiles anyway)

**Comment by rsuter** [comment]
I've added a second unit test project with the same tests but for the .NET 4 library: 
https://github.com/NJsonSchema/NJsonSchema/commit/8bc3e1d8fa0fbda2c512dbdeb5f5fdbd77b41045

Now we have to fix the broken tests...

**Comment by rsuter** [comment]
Ok, now all unit tests are fixed: https://github.com/NJsonSchema/NJsonSchema/commit/e63014c2086ee6ade073f0e79d8aa9015c8e06ad

Release v4.28, soon

**Comment by TekkBob** [comment]
Great! Thanks!

Am 11. Oktober 2016 17:19:10 MESZ, schrieb Rico Suter <notifications@github.com>:
>Ok, now all unit tests are fixed:
>https://github.com/NJsonSchema/NJsonSchema/commit/e63014c2086ee6ade073f0e79d8aa9015c8e06ad
>
>Release v4.28, soon
