### ISSUE TITLE
Date format & Pattern is not getting matched.

### ISSUE THREAD

**Issue by khairnarnitin** [NJsonSchema/NJsonSchema#22]
Hi,
Below data is valid for given schema but we are getting pattern mismatch error.
Sample Schema

	{
		"$schema": "http://json-schema.org/draft-04/schema#",
		"type": "object",
		"properties": {
			"SimpleDate": {
				 "type": "string",
				  "format": "date-time"
			  },
			"PatternDate": {
				"type": "string",
				"pattern" : "(^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}T[0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}Z$|^$)"
			}
		}
	}

Sample Data

	{
	  "SimpleDate":"2012-05-18T00:00:00Z",
	  "PatternDate":"2012-11-07T00:00:00Z"
	}

Here I found two issues. 

1. If SimpleDate format is "date" then, it should accept only "2015-05-18" & not "2012-05-18T00:00:00Z".
2. Even if the PatternDate value is matching to the PatternDate schema. it is throw PatternMismatch error.

tried to verify it with 
http://www.jsonschemavalidator.net/
it does not return any validation error.

**Comment by rsuter** [comment]
The problem is that Json.NET automatically converts the date into a datetime and thus the pattern no longer matches...

**Comment by khairnarnitin** [comment]
Yes I have investigated & found the same. I was trying to figure out if we can use raw json value while validating with pattern.

**Comment by rsuter** [comment]
It seems that there is no way to get the raw JSON value... A workaround may be to convert the value back to a string. The problem is, that this method works not in every case, because sometimes other date-time patterns are also transformed to a DateTime: 

        private void ValidateString(JToken token, string propertyName, string propertyPath, List<ValidationError> errors)
        {
            var isString = token.Type == JTokenType.String || token.Type == JTokenType.Date ||
                           token.Type == JTokenType.Guid || token.Type == JTokenType.TimeSpan ||
                           token.Type == JTokenType.Uri;

            if (isString)
            {
                var value = token.Type == JTokenType.Date ? token.Value<DateTime>().ToString("yyyy-MM-ddTHH:mm:ssK") : token.Value<string>();
                if (value != null)

**Comment by rsuter** [comment]
I've added your unit test and this possible fix (commented out): https://github.com/NJsonSchema/NJsonSchema/commit/f8074826eabbf084c11775400a1bc37734c89021

**Comment by rsuter** [comment]
See SO question: http://stackoverflow.com/questions/35138346/jtoken-get-raw-json-value

**Comment by rsuter** [comment]
I just fixed the problem, you can now use Validate(string json) to disable automatic DateTime parsing and thus the datetime is parsed as string... This way your pattern should correctly match. Also have a look at the unit tests: https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema.Tests/Samples/SampleTests.cs

Commit: https://github.com/NJsonSchema/NJsonSchema/commit/2699830357c464fa70c143fdf7c9df30c7ee1544
Version: 1.30

**Comment by SaltyDH** [comment]
Just trying to get my head around this problem, the documentation here: https://github.com/RSuter/NJsonSchema/wiki/JsonSchema4#validatestring-vs-validatejtoken 

says you should go with the Json string rather than a JToken for these sorts of problems. Its seems that the tests and the JsonSchemaValidation immediately calls JToken.Parse so is the documentation no longer accurate?
