### ISSUE TITLE
Invalid C# enum names generated

### ISSUE THREAD

**Issue by alm-psarno** [NJsonSchema/NJsonSchema#228]
I have a JSON schema with an enum that is not directly translatable to .Net due to the enum values.

## JSON

```
  "CompType": {
   "type": "string",
   "enum": [
    "$",
    "%"
   ]
  }
```
When run through the codegen, the C# enum becomes:

## C#
```
    [GeneratedCode("NJsonSchema", "5.2.6135.25892")]
    public enum CompType
    {
        [EnumMember(Value = "$")]
        $ = 0,
    
        [EnumMember(Value = "%")]
        % = 1,
    
    }
```
It's obvious why this is being generated this way ... and why it isn't going to compile.  I was about to point out that extraneous comma, until I remember this is by design (pretty much for this exact purpose)!

Regarding the enum field names, am I missing an option that I should be passing here?

**Comment by rsuter** [comment]
Can you please this the new EnumNameGenerator setting and report back?
