### ISSUE TITLE
Schemas with #ref in them

### ISSUE THREAD

**Issue by DotNetRockStar** [NJsonSchema/NJsonSchema#239]
Hi there.

I am attempting to create c# classes from a swagger document that contains multiple definitions that may link to one another using #ref.
Example: See "definitions" node here: http://api.dynamicapis.com/swagger/docs/v1

How can I successfully create a list of classes for each definition within this document?

**Comment by rsuter** [comment]
This is a swagger document (not a json schema), try using nswag to generate the code for this spec (nswag internally uses njsonschema): http://nswag.org

**Comment by DotNetRockStar** [comment]
There is json schema in there in the "definitions" section.  Those are json schema objects.  Here is an example of one:

```
{
"type": "object",
"properties": {
"Version": {
"type": "string"
},
"Title": {
"type": "string"
},
"Description": {
"type": "string"
},
"TermsOfService": {
"type": "string"
},
"Contact": {
"$ref": "#/definitions/DynamicApis.Entities.Swagger.Contact"
},
"License": {
"$ref": "#/definitions/DynamicApis.Entities.Swagger.License"
}
}
}
```

**Comment by DotNetRockStar** [comment]
I'll take a look at nswag and see how they are doing it.  Thanks.

**Comment by rsuter** [comment]
You can try the ui (NSwagStudio), its a three minute process... Please report if it worked.
