### ISSUE TITLE
Required fields on null value

### ISSUE THREAD

**Issue by Geoffrey-A** [NJsonSchema/NJsonSchema#240]
NJsonSchema rejects `[{"value":2},null]` for the following schema, but [Newtonsoft’s Json.NET Schema](http://www.jsonschemavalidator.net/) accepts it:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": [ "object", "null" ],
    "properties": {
      "value": { "type": "integer" }
    },
    "required": [ "value" ],
    "additionalProperties": false
  }
}
```

What is the correct behaviour?
What is the suggested workaround?

**Comment by rsuter** [comment]
Release v5.13, available in 5 minutes. Thanks for reporting...

**Comment by Geoffrey-A** [comment]
I have confirmed the fix.
Thank you very much for your hard work.
