### ISSUE TITLE
Implementing ITypeNameGenerator, IPropertyNameGenerator doesn't work as excpected  

### ISSUE THREAD

**Issue by MoamenMohamed** [NJsonSchema/NJsonSchema#244]
When creating a C# class using `CSharpCodeGenerator `it converts type names and properties names into a **CamalCase** format it is cool but for some reason i don't need that so i have implemented the interfaces `ITypeNameGenerator`, `IPropertyNameGenerator ` and set them in `CSharpCodeGenerator ` code generator setting parameter however it still converts them to **CamalCase** by debugging i found that:
- In Class `TypeResolverBase ` the  method `GetOrGenerateTypeName`  executes this line;
`_generatedTypeNames[schema] = ConversionUtilities.ConvertToUpperCamelCase(typeName, true);`
 for both the default generator or the user defined one.
- In Class `PropertyModel `the `Constructor ` executes this line;
 `PropertyName = ConversionUtilities.ConvertToUpperCamelCase(GetGeneratedPropertyName(), true);`
for both the default generator or the user defined one.

**Comment by rsuter** [comment]
I think we should remove this to upper code and provide default type/property name generators for ts and cs output...

**Comment by MoamenMohamed** [comment]
I ended up with creating an **enum** NamingStyle 
```
public enum NamingStyle : byte
    {
        /// <summary>Ignore style</summary>
        Ignore = 0,
        /// <summary>The upper camel case.</summary>
        UpperCamelCase,
        /// <summary>The lower camel case.</summary>
        LowerCamelCase,
        /// <summary>The upper camel case with alpha.</summary>
        UpperCamelCaseWithAlpha,
        /// <summary>The lower camel case with alpha.</summary>
        LowerCamelCaseWithAlpha
    }
```
, extended the **CodeGeneratorSettingsBase** with three properties 
```
public NamingStyle EnumsNamingStyle { get; set; } = NamingStyle.Ignore;
public NamingStyle PropertiesNamingStyle { get; set; } = NamingStyle.Ignore;
public NamingStyle TypesNamingStyle { get; set; } = NamingStyle.Ignore;
```
and  add this method to **ConversionUtilities** which i use when ever i create an enum, property or type
```
public static string ApplyNamingStyle(string input, NamingStyle namingStyle)
        {
            // Apply naming style.
            switch (namingStyle)
            {
                case NamingStyle.Ignore:
                    break;

                case NamingStyle.UpperCamelCase:
                    input = ConversionUtilities.ConvertToUpperCamelCase(input, false);
                    break;

                case NamingStyle.LowerCamelCase:
                    input = ConversionUtilities.ConvertToLowerCamelCase(input, false);
                    break;

                case NamingStyle.UpperCamelCaseWithAlpha:
                    input = ConversionUtilities.ConvertToUpperCamelCase(input, true);
                    break;

                case NamingStyle.LowerCamelCaseWithAlpha:
                    input = ConversionUtilities.ConvertToLowerCamelCase(input, true);
                    break;
            }

            return input;
        }
```
 
For example: 
`_generatedTypeNames[schema] = ConversionUtilities.ConvertToUpperCamelCase(typeName, true);`
will be
`_generatedTypeNames[schema] = ConversionUtilities.ApplyNamingStyle(typeName, _namingStyle);`

**Comment by MoamenMohamed** [comment]
enum & property are fixed but the **TypeName** still not working because of the line **108** in **TypeResolverBase.cs**
