### ISSUE TITLE
Support for DefaultValue attribute

### ISSUE THREAD

**Issue by zinvob** [NJsonSchema/NJsonSchema#25]
Your component is a very good contribution to the community. I've testet it out now and things look great. For now all I miss is support for "default" :) Could you add support for this?

It would be nice to have it through the System.ComponentModel.DefaultValueAttribute

**Comment by rsuter** [comment]
Feature added in https://github.com/NJsonSchema/NJsonSchema/commit/085e36d0c2d8a76fe9678f697c0491dedb8c08ea, v1.31

**Comment by rsuter** [comment]
Pushed to nuget

**Comment by rsuter** [comment]
Now the `default` property of the JSON Schema is set if the C# attribute is available...
