### ISSUE TITLE
Slow performance for large json strings

### ISSUE THREAD

**Issue by littlebiirdy** [NJsonSchema/NJsonSchema#253]
Performance is slow when validating large json strings.
One issue seems to be that JsonSchemaValidator.GetTypes() calls 
"Enum.GetValues(typeof(JsonObjectType)).Cast<JsonObjectType>()"
every time it is called.  As this won't change, the value could be calculated once and then just the filtering applied per call to GetTypes().  System.RuntimeTypes.GetEnumValues shows up as 10% of my validation time for a large JSON string in a profiler.

**Comment by rsuter** [comment]
The validator is currently not really optimized... I'm sure it can be made much faster by doing some profiling. 

I'm developing the library mainly for NSwag (http://nswag.org) and only use the JsonSchemaGenerator and not the JsonSchemaValidator. 

Please create PRs for optimizing the validator, but try to keep the code as simple as possible...

**Comment by rsuter** [comment]
Can you provide sample data (JSON and Schema) to do performance optimizations with?

**Comment by rsuter** [comment]
This particular performance improvement has been implemented in v5.19

**Comment by littlebiirdy** [comment]
Thanks for the fix!

I'm testing on an edge case where we have an array of 85,000 objects at the top level of the schema (the object is pretty simple and just has 4 integers in it with a minimum of 0).

Testing with the latest version seems to be ~500ms faster (really rough figure, i only ran a few quick tests with very little isolation).

Haven't looked into the rest of the performance in detail.  This function just stood out in the profiler as something easy to fix for a good gain.
