### ISSUE TITLE
How can I validate Json Scheam?

### ISSUE THREAD

**Issue by sithwin** [NJsonSchema/NJsonSchema#255]
I have Json Schema

`{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"body": {
			"id": "body",
			"name": "body",
			"title": "body",
			"type": "string"
		},
		"title": {
			"id": "title",
			"name": "title",
			"title": "title",
			"type": "string"
		}
	},
	"additionalProperties": false,
	"required": [
		"body",
		"title"
	]
}`

I would like to validate it but couldn't find a method to validate. 
Pls advice.

Thanks!

**Comment by rsuter** [comment]
var schema = JsonSchema4.FromJson(...);
var errors = schema.Validate(...);
