### ISSUE TITLE
Would be nice to support custom validation

### ISSUE THREAD

**Issue by globeport** [NJsonSchema/NJsonSchema#258]
Would be nice to be able to add custom validators to be used, for example, for custom string formats.

**Comment by rsuter** [comment]
Yes, we could add support for this via JsonSchemaValidator inheritance

**Comment by rsuter** [comment]
With this commit, you can inherit from JsonSchemaValidator and override Validate(...) and depending of some condition (ie. format is set) do your own validation or return base implementation...

**Comment by rsuter** [comment]
v6.0

**Comment by globeport** [comment]
great! thanks :)

**Comment by globeport** [comment]
Can you make JsonSchemaValidator public to support this. Thanks.

**Comment by rsuter** [comment]
Sorry, totally missed that...

**Comment by globeport** [comment]
Another issue with this. The logic for Anyof, AllOf, One of and Not calls the Validate method on the JsonSchema4 class. This instantiates a new JsonSchemaValidator object. So custom validation is not possible here. I think the Validate method on the calling JsonSchemaValidator can be used in these cases?

**Comment by rsuter** [comment]
v6.3

**Comment by globeport** [comment]
👍

**Comment by globeport** [comment]
hmm, theres another problem here. For example, if I have the following 

```
"anyOf": [
        {"required": [ "Property1" ]},
        {"required": [ "Property2" ]},
        {"required": [ "Property3" ]}
    ]
```
The child schemas don't seem to have reference to the properties in their scope

**Comment by rsuter** [comment]
Is this even allowed?

**Comment by globeport** [comment]
I've certainly seen examples of it by searching around. 

http://stackoverflow.com/questions/24023536/json-schema-how-do-i-require-one-field-or-another-or-one-of-two-others-but-no

**Comment by globeport** [comment]
Validates as expected with Json.Net schema.
