### ISSUE TITLE
Q: Hook for custom resolving of $ref references?

### ISSUE THREAD

**Issue by diaconesq** [NJsonSchema/NJsonSchema#263]
Hello, 

I have a scenario where I need to parse a bunch of JSON Schema files that have $ref's to one another, using   fully specified 'http://...' paths. The files live on disk so I can read the "top level" schema using 

> JsonSchema4.FromFile(...)

but I'd like to actually have the $ref's to also be read from disk (or maybe in the future from embedded resources) - anyway, no network calls. 

Is there a way to hook a custom schema resolver (?) to have control over where the $ref's are read from?

I thought about using relative $ref instead of absolute ones, but the $ref URLs look like 'http://server/path/my-schema#' - they don't specify the .json extension that the files actually have on disk.

**Comment by diaconesq** [comment]
Update: JSON.NET Schema seems to have this functionality:

http://www.newtonsoft.com/jsonschema/help/html/JsonUrlSchemaResolverRelative.htm

Is there anything similar inside NJsonSchema?

**Comment by rsuter** [comment]
You have this overload: 

        public static JsonSchema4 FromUrl(string url, JsonReferenceResolver jsonReferenceResolver)

However JsonReferenceResolver does not have a virtual method and no base class/interface...

I think we should set the JsonReferenceResolver.ResolveReference method as virtual so that you can provide your own implementation... 

Would this be enough?

**Comment by diaconesq** [comment]
It would work. It wouldn't be ideal though.
For my particular purpose, I think `JRR.ResolveFileReference(...)` and `JRR.ResolveUrlReference(...)` should be visible - at least protected and virtual, so that a class derived from JRR could leverage the caching logic that's already there.

But I see another approach that's more in line with the 'single responsibility principle' - basically leave all logic as is, and just allow replacing the low-level "get me the bytes" methods: 
The reference-resolving logic eventually (recursively) calls JsonSchema4.FromUrl(...) or JsonSchema4.FromFile(...) which in turn call DynamicApis.FileReadAllText(...) or DynamicApis.HttpGet(...). 

If these DynamicApis.* calls would be pluggable, it would just allow me to implement an URL rewriting of sorts, without me having to know or care about caching.

I'll try to do a PR for this, and you can decide if it makes sense for a more general audience.

**Comment by rsuter** [comment]
Is the latest change fine for you? I think you should change the JRR behavior and not the DynamicApis behavior, because reading a file from a given path/URL should always use the expected location...

**Comment by rsuter** [comment]
This is now available in the latest version...
