### ISSUE TITLE
StackOverflow on IEnumberable types in .Net 4.0 (Version > 5.20.6175.31167)

### ISSUE THREAD

**Issue by HyperPollok** [NJsonSchema/NJsonSchema#266]
This code causes an StackOverflow
```
void Main(string[] args)
{
    Console.WriteLine(NJsonSchema.JsonSchema4.FromType<IEnumerable<Tuple<string, string>>>().ToJson());
    Console.ReadKey(false);
}
```

The infinite loop seems to be caused by the GetJsonPath method.

Great work so far.

**Comment by rsuter** [comment]
I cannot reproduce this in the latest version (just copied the first line into the demo app).

**Comment by HyperPollok** [comment]
Hi,

I am still able to reproduce the StackOverflow in VS2015 .Net 4.5, event in the latest release (d1b1c2a), the latest master (3aa08f6) and the latest NuGET-Package (6.5.6190.16910).

I just cloned the source and copied the following line into the DemoApp>Program.cs>Main to reproduce the error:

```
Console.WriteLine(NJsonSchema.JsonSchema4.FromType<System.Collections.Generic.IEnumerable<Tuple<string, string>>>().ToJson());
```

I also tried the TestProjects with the following test in VS2015:

```
        [TestMethod]
        public void When_type_is_enumberable_it_should_not_stackoverflow_on_JSON_generation()
        {
            //// Generate JSON
            var result = NJsonSchema.JsonSchema4.FromType<System.Collections.Generic.IEnumerable<System.Tuple<string, string>>>().ToJson();

            //// Should be reached and not StackOverflowed
            Assert.IsTrue(!string.IsNullOrEmpty(result));
        }
```

At least NuGET-Test with a test from scratch 
[BadTest4.5.zip](https://github.com/NJsonSchema/NJsonSchema/files/645811/BadTest4.5.zip)

I hope, I was able to help you out further.

Thanks
