### ISSUE TITLE
Get line number and data from ValidationError

### ISSUE THREAD

**Issue by amoedoamorim** [NJsonSchema/NJsonSchema#267]
It would be nice if we could have the number of the line where an error occurs and the data itself from that line. Rather than showing only the error Kind, Path or Property, providing the user with line number and the data on that line might be a more palpable information.

More or less, the same wish as in this StackOverflow question:
http://stackoverflow.com/questions/40636517/trying-to-retrieve-linenumber-information-from-njsonschema-validationerrors

Line number would be enough, as the string could be extracted from the original content, once you get the line number.

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/pull/268
