### ISSUE TITLE
Support for nullable Primitives

### ISSUE THREAD

**Issue by justcoding121** [NJsonSchema/NJsonSchema#27]
The schema generated by NJsonSchema doesn't looks like supporting nullable primitive types. Instead the schema looks similar to that of non-nullable types, for example int, datetime & string. This is a feature request.

**Comment by rsuter** [comment]
Can you post some sample code and the expected outcome...

**Comment by justcoding121** [comment]
I am not sure what the expected outcome would be. I was using the generated schema for the following class to feed [JsonEditor](https://github.com/jdorn/json-editor). Previously I used [JSON.Net schema generator](https://www.nuget.org/packages/Newtonsoft.Json.Schema) and JsonEditor would give me an option to set Name and Size either null or a value. However when I used NJSONschema generator json-editor wouldn't give me any optional text boxes, rather they look like required properties.

I switched to NJsonSchema to get the benefits of Json version 4. Not sure if version 4 wouldn't allow nullable properties. So.

```
public class ClassRoom
{
public int Id {get;set;}
public string? Name {get;set;}
public int? size {get;set;}
}
```

**Comment by rsuter** [comment]
The class: 

    public class ClassRoom
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int? Size { get; set; }
    }

With `NJsonSchema`: 

	{
	  "typeName": "ClassRoom",
	  "additionalProperties": false,
	  "type": "object",
	  "required": [
		"Id"
	  ],
	  "properties": {
		"Id": {
		  "type": "integer"
		},
		"Name": {
		  "type": "string"
		},
		"Size": {
		  "type": "integer"
		}
	  },
	  "$schema": "http://json-schema.org/draft-04/schema#"
	}
	
With `Newtonsoft.Json.Schema`: 	
	
	{
	  "type": "object",
	  "properties": {
		"Id": {
		  "type": "integer"
		},
		"Name": {
		  "type": [
			"string",
			"null"
		  ]
		},
		"Size": {
		  "type": [
			"integer",
			"null"
		  ]
		}
	  },
	  "required": [
		"Id",
		"Name",
		"Size"
	  ]
	}

**Comment by vamsitp** [comment]
So if we do not provide a "Required" attribute, shouldn't the JsonSchema4.Validate(...) allow nulls (say for **_int? size _** above)? I see a validation error - **_NJsonSchema.Validation.ValidationErrorKind.IntegerExpected_** when I provide a "null" in the JSON.

**Comment by rsuter** [comment]
Can you provide the exact schema end data you tested with?

**Comment by vamsitp** [comment]
[NJsonSchemaTest.zip](https://github.com/NJsonSchema/NJsonSchema/files/154372/NJsonSchemaTest.zip)

You can check the attached console app for various scenarios. Let me know if I'm missing something.

**Comment by rsuter** [comment]
For AnyOf, you need to check the AnyOf collection and not the type of the property...

**Comment by rsuter** [comment]
... None is correct in this case

**Comment by rsuter** [comment]
see https://github.com/json-schema/json-schema/issues/224, so the validator works correctly... Only problem is the generator

**Comment by vamsitp** [comment]
So, the link says the point 2) above should be supported (`"Size": { "type": ["integer", "null"] }`). But it doesn't seem to work in the sample I attached.

**Comment by rsuter** [comment]
Point 2 is fixed with v1.33 https://github.com/NJsonSchema/NJsonSchema/commit/28afe4996159f1191a1e8ccb251d29eec926c92d

**Comment by rsuter** [comment]
Point 1 is correctly validated as invalid

**Comment by rsuter** [comment]
Point 3 is correctly validated as valid (schema type is None and AnyOf collection is loaded)

**Comment by rsuter** [comment]
The only open problem: The generated JSON Schema is wrong and should look like the second schema (Newtonsoft.Json.Schema)... Ill look into this ASAP.

**Comment by vamsitp** [comment]
Thanks, point 2 is what I'm interested in. Shall wait for the NUGET to be available.

**Comment by rsuter** [comment]
The nuget will be available in one or two days, ill fix the generator too and have to test everything..

**Comment by rsuter** [comment]
Ok, v1.34 is live.. please check if everything is working for you and what has to be fixed...

**Comment by vamsitp** [comment]
OK, found another discrepancy (w.r.t **Items **property)...Shall raise a new issue.

**Comment by rsuter** [comment]
Yes, please open a new issue. Currently i mostly use the code generation part to pus http://nswag.org this is why the validation part may have some flaws...
