### ISSUE TITLE
Figure out the actual URI of a $ref ?

### ISSUE THREAD

**Issue by diaconesq** [NJsonSchema/NJsonSchema#271]
Hello, 

I'm working with a schema that uses a 'definitions' region and has properties that reference to these definitions. 
I'm trying to figure out if several properties refer to the same sub-schema. 
I found `HasSchemaReference` under the property object (which is true if $ref is used), and `SchemaReference` that actually points to the sub-schema. 
However, I was hoping to find the actual path of the sub-schema under `SchemaReference`.
In the example below, that would be `"#/definitions/myDef"`

Alternatively, I'd be fine with some other thing I could use as an unique identifier for the sub-schema.

Is there a way to achieve this other than comparing the actual pointers to the sub-schema objects (a la `object.ReferenceEquals(...)`?

This is the schema that I'm using as an example.
I want to programatically tell if 'simpleRef' and 'otherProp' reference the same thing.

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "myDef": {
      "properties": {
        "myDef_prop1": {
          "type": "integer"
        },
        "myDef_prop2": {
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "simpleRef": {
      "$ref": "#/definitions/myDef"
    },
    "otherProp": {
      "$ref": "#/definitions/myDef"
    }
  }
}
```

**Comment by diaconesq** [comment]
I sort of found a way: 
1. Force building of schema reference paths on the schema:
 JsonSchemaReferenceUtilities.UpdateSchemaReferencePaths(jsonSchema, ...)
2. Read (private) property `SchemaReferencePath`. It contains the expected "#/definitions/myDef". 

But this is hacky. Is there any public property where I can read this from?

**Comment by rsuter** [comment]
Can't you use: 

    var path = JsonPathUtilities.GetJsonPath(object root, object searchedObject, JsonSchemaResolver schemaResolver = null)

For that?

**Comment by diaconesq** [comment]
Thank you, works beautifully. Also works with external refs, if I use `SchemaReference.FindRoot()` as the root parameter.
