### ISSUE TITLE
Schema.ActualProperties explodes with StackOverflow exception on schema containing cyclic reference

### ISSUE THREAD

**Issue by diaconesq** [NJsonSchema/NJsonSchema#274]
While I can understand this to happen for a nonsensical schema containing cyclic references, it's still not a nice experience. If validating user-defined schemas (and using the property `ActualProperties`). there's no way to guard against a DoS.

The workaround is, of course, not to use that property. But then why have it in the first place?

I would expect a recurrence depth limit check. 

Here's an input that triggers it:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "definitions": {
    "myDef": {
      "allOf": [
        {
          "properties": {
            "myDef_prop1": {
              "type": "integer"
            },
          }
        },
        {
          "$ref" : "#/definitions/myDef"
        }
      ]
    }
  },
  "allOf": [
    {
      "$ref": "#/definitions/myDef"
    }
  ],
  "properties": {
    "topProp": {
      "$ref": "#/definitions/myDef"
    },
    "topArrayProp": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/myDef"
      }
    }
  },
  "required": [
    "pages"
  ]
}

```

**Comment by rsuter** [comment]
Yes, it should throw something like:

    new InvalidOperationException("Cyclic references detected.");
