### ISSUE TITLE
JsonSchema4.FromUrlAsync failed with collection was modified error

### ISSUE THREAD

**Issue by zivabratz** [NJsonSchema/NJsonSchema#288]
I'm trying to create scheme for the following URL :
JsonSchema4 schema = JsonSchema4.FromUrlAsync("http://schemas.sportradar.com/bsa/json/v1/endpoints/soccer/team_profile.json").Result
i'm getting error : Collection was modified; enumeration operation may not execute.
Hope you can help to find the reason for the failure.

**Comment by diaconesq** [comment]
I saw this today as well on some schemas. Using v.7.3.6214.20986

**Comment by rsuter** [comment]
v7.4

**Comment by diaconesq** [comment]
Wow, this is paid-subscription level turn-around time !
Confirmed, it works for my inputs as well. 

Thank you!
