### ISSUE TITLE
Bug: type array with more than 1 primitive type does not validate correctly

### ISSUE THREAD

**Issue by rutger-dijkstra** [NJsonSchema/NJsonSchema#29]
A property schema with a Type that encompasses more than 1 primitive type never validates successfully. Reproducible by adding the following unit test to ObjectValidationTests.cs:

```cs
[TestMethod]
public void When_property_matches_one_of_the_types_then_it_should_succeed()
{
    //// Arrange
    var schema = new JsonSchema4();
    schema.Type = JsonObjectType.Object;
    schema.Properties["Foo"] = new JsonProperty
    {
        Type = JsonObjectType.Number | JsonObjectType.Null
    };

    var token = new JObject();
    token["Foo"] = new JValue(5);

    //// Act
    var errors = schema.Validate(token);

    //// Assert
    Assert.AreEqual(0, errors.Count());
}
```

The errors collection will, in fact, contain 2 NullExpected errors

**Comment by rsuter** [comment]
Your PR introduced some additional validation bugs when starting the JSON Schema validation suite... I fixed it and added your unit tests: https://github.com/NJsonSchema/NJsonSchema/commit/28afe4996159f1191a1e8ccb251d29eec926c92d
