### ISSUE TITLE
What happened to JsonSchema4.TypeNameRaw?

### ISSUE THREAD

**Issue by paulomorgado** [NJsonSchema/NJsonSchema#301]
I'm trying to upgrade some code that uses NJsonSchema versio 5.20 to version 7.6 and there was a `JsonSchema4.TypeNameRaw` property that no longer exists.

What's the replacement?

**Comment by rsuter** [comment]
The typename is completely infered from the "definitions" key (or "title" property)

**Comment by paulomorgado** [comment]
Thanks!
