### ISSUE TITLE
library wrongly claims document is not valid

### ISSUE THREAD

**Issue by mkaut** [NJsonSchema/NJsonSchema#322]
In the following small [example](https://dl.dropboxusercontent.com/u/22320179/input_json_test.zip), VisualJsonEditor (using NJsonSchema) claims a JSON document is not valid, even though other validators say it is OK.
It seems to require several objects, even if they are not marked as "required" in the schema.

See https://github.com/rsuter/VisualJsonEditor/issues/14

**Comment by rsuter** [comment]
I think this was actually a bug in VisualJsonEditor, please try again with v2.0

**Comment by mkaut** [comment]
I originally filed the bug against VisualJsonEditor and was told that 
the problem is in NJsonSchema and should file a bug there.

I would like to try it with VJE v 2.0, but the latest version I could 
find is 1.1.


Best regards,
Michal Kaut

**Comment by rsuter** [comment]
Download latest: https://ci.appveyor.com/project/rsuter/visualjsoneditor/build/65/artifacts

**Comment by mkaut** [comment]
That worked, thanks a lot.

Best regards,
Michal
