### ISSUE TITLE
Generated generic type for typescript with wrong syntax

### ISSUE THREAD

**Issue by mkjeff** [NJsonSchema/NJsonSchema#33]
C#:
``
 Generic<T> 
``

Typescript
``
Generic[T] // wrong syntax
``

it will be better if sharing generic open type

**Comment by rsuter** [comment]
Can you provide a sample input class which is wrongly converted?

**Comment by mkjeff** [comment]
Sorry, I did not clarify the scenario. I used swagger schema JSON as input(NSwag).
I found a workarround, SchemaId configuration can fix this. [https://github.com/domaindrivendev/Swashbuckle/issues/600#issuecomment-171777175](url)
`c.SchemaIds(type => type.FriendlyId().Replace("[", "Of").Replace("]", ""));`

**Comment by rsuter** [comment]
So the `FriendlyId` is the key in the Swagger's `definitions` list?
