### ISSUE TITLE
Question: How to create External reference $ref for Json Schema manually

### ISSUE THREAD

**Issue by moh-hassan** [NJsonSchema/NJsonSchema#337]
I find NjsonSchema very useful and start using it. 
I try to build the following schema manually
   
        {
           'type': 'object',
           title = 'employee',
           'properties': {
          'name': {'type':'string'},
           'addresses': {
             'type': 'array',
            'items': {'$ref': 'http://json-schema.org/address'}
          }
        }
       }

I use the following code:
   
            var schema = new JsonSchema4
            {
                Type = JsonObjectType.Object,
                Title = "personal" ,
                AllowAdditionalProperties = false
        }; 
            var p = new JsonProperty
            {
                Type = JsonObjectType.String,
            };
            schema.Properties.Add("name", p);   
            var p2 = new JsonProperty
            {
                Type = JsonObjectType.Array,
                 //??????????
                //how to add $ref as in the following example
                // 'items': {'$ref': 'http://json-schema.org/address'}
            };
            schema.Properties.Add("address", p2);      
How to add $ref as given in my comment in code.
Best Regards,

**Comment by rsuter** [comment]
Can we close this?

**Comment by moh-hassan** [comment]
Hi  rsuter,
Thanks for help and responding to my issue.
Kindly, how to call the new feature. to get:
 'items': {'$ref': 'http://json-schema.org/address'}
Best Regards,

**Comment by moh-hassan** [comment]
I modified my original code and  used the following code (I hope that is the official way to use the API)
(I'm using the last version:  8.14.6289.34345)

             //implementing:  'items': {'$ref': 'http://json-schema.org/address'}
            var referenceToSchema = new JsonSchema4 { DocumentPath = "http://json-schema.org/address"   };
            var p2 = new JsonProperty
            {
                Type = JsonObjectType.Array,
                Item = new JsonSchema4 { SchemaReference = referenceToSchema }
            };
            schema.Properties.Add("address", p2);
           Console.WriteLine(schema.ToJson());

The generated schema is:

			{
			  "$schema": "http://json-schema.org/draft-04/schema#",
			  "type": "object",
			  "title": "personal",
			  "additionalProperties": false,
			  "properties": {
				"name": {
				  "type": "string"
				},
				"address": {
				  "type": "array",
				  "items": {
					"$ref": "http://json-schema.org/address#"
				  }
				}
			  }
			}

It's what i need :) :) , but i find "#"  at  the end of the path.
I want:  "$ref": "http://json-schema.org/address"
The generated schema is:  "$ref": "http://json-schema.org/address#" 

How to remove "#" from the path ,and the pas  is written AS IS?

Thanks

**Comment by moh-hassan** [comment]
I checked the loading of the generated schema with the referenced schema  and it's loaded correctly.
I used the following code:

             Console.WriteLine("-------------- Reloading the generated schema with concatened # -----------");
            // Reloading the generated schema with # concatenated at end of URL path
            //it should resolve the path and reload the referenced schema correctly
            var schema3 = await JsonSchema4.FromJsonAsync(schema.ToJson());
            var data = schema3.ToJson();
            Console.WriteLine(data);   // the schema and the referenced schema is loaded correctly

 The result can be reviewed at Gist:  https://gist.github.com/moh-hassan/e53923ea9a62e850d6e8db84702c122f

Anyway, the "#" at the end  of Uri path match the standard of Json Draft 4 at: http://json-schema.org/latest/json-schema-core.html

**Conclusion:**
The library v 8.14.6289.34345 create the external references correctly.
You can Close the issue. :) :)

Best regards,
