### ISSUE TITLE
Modify format based on custom DataType attribute

### ISSUE THREAD

**Issue by AndyEdmonds** [NJsonSchema/NJsonSchema#34]
Hi, 
First of all thanks for a great product.
I'm using this with jdorn/json-editor. This editor uses format elements to describe non-standard format requests, such as, for an object, `"format": "grid"` displaying that object in a grid rather than tabular format.
Currently you output formatting based on data types, ignoring (I think) the `DataTypeAttibute`.
It would be good to be able to inject specific formatting requirements through the DataType attribute and specifically the datatype.custom type. Perhaps there's another simpler way to do this, but I would like to be able to influence the format elements in a schema by changing the attributes on the class member declarations.

**Comment by rsuter** [comment]
So this is for the JSON Schema generator from a C# type? Can you provide a sample?

**Comment by AndyEdmonds** [comment]
`public` class Connectivity
    {
        [Required]
        [Display(Name = "External connections", Description = "Connections to external SaaS vendors triggered by or triggering projects")]
        public List<Connector> connectors { get; set; }
    }`
`public enum ConnectorType { twilio, sendgrid, skype, facebook, custom}
    public class Connector
    {
        [Required]
        [Display(Name = "SaaS vendor", Description = "The SaaS service you are connecting to.")]
        public ConnectorType type { get; set; }

        [Required]
        [Display(Name = "Your ID", Description = "The SaaS service ID that identifies your account")]
        public string id { get; set; }

        [Required]
        [Display(Name = "Your API key", Description = "The SaaS service secret token or API key")]
        public string key { get; set; }

        [Display(Name = "The destination address", Description = "The destination of any transmission over a public medium")]
        public string dest { get; set; }
    }`
creates the schema:
`{
  "typeName": "Connectivity",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "connectors"
  ],
  "properties": {
    "connectors": {
      "items": {
        "typeName": "Connector",
        "additionalProperties": false,
        "type": "object",
        "required": [
          "type",
          "id",
          "key"
        ],
        "properties": {
          "type": {
            "typeName": "ConnectorType",
            "type": "integer",
            "enum": [
              0,
              1,
              2,
              3,
              4
            ],
            "enumNames": [
              "twilio",
              "sendgrid",
              "skype",
              "facebook",
              "custom"
            ],
            "title": "SaaS vendor",
            "description": "The SaaS service you are connecting to."
          },
          "id": {
            "type": "string",
            "title": "Your ID",
            "description": "The SaaS service ID that identifies your account"
          },
          "key": {
            "type": "string",
            "title": "Your API key",
            "description": "The SaaS service secret token or API key"
          },
          "dest": {
            "type": [
              "null",
              "string"
            ],
            "title": "The destination address",
            "description": "The destination of any transmission over a public medium"
          }
        }
      },
      "type": "array",
      "title": "External connections",
      "description": "Connections to external SaaS vendors triggered by or triggering projects"
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
`
In order to get json-editor to display this in grid format, the first part of the schema should be:
``{
  "typeName": "Connectivity",
  "additionalProperties": false,
  "type": "object",
  "format": "grid",
  "required": [
    "connectors"
  ],

`
I'm looking for some method to inject this.  I want to use your tool to dynamically create the json so that changes to the classes are automatically reflected in the editor.

**Comment by rsuter** [comment]
Can't you post process the generated schema and add the additional `format` strings?

We could add a custom NSwag attribute (in the NSwag.Annotations NuGet package) like this: 

    [JsonFormat("grid")]
    public class Connectivity
    {
        public List<Connector> connectors { get; set; }
    }

However I'm not yet sure if this is a good idea (as it is a custom JSON Schema extension)

**Comment by AndyEdmonds** [comment]
Hi, I certainly can post process, and that's the interim fix, but it's clumsy.  Your solution looks good.

**Comment by rsuter** [comment]
Hmm, the problem is, that there is currently no annotations NuGet... can we use an attribute of the .NET framework or Json.NET? Is `DataTypeAttibute` a fit?

**Comment by AndyEdmonds** [comment]
That was my guess. There is a custom datatype defined. Also, and I should probably make this a separate issue, do you support readOnly? It's in the Json schema spec, and the matching attribute is 
``[ReadOnly(true)]``

**Comment by rsuter** [comment]
The readonly keyword has been removed: http://json-schema.org/latest/json-schema-hypermedia.html#anchor15

![image](https://cloud.githubusercontent.com/assets/2603405/13611824/b5d2b658-e564-11e5-8437-a670ea4f2a66.png)

**Comment by rsuter** [comment]
And btw: Using the `format` property for describing the UI is wrong. The property is intended to describe the format of the value (i.e. how to parse it) and not how to display it (i.e. list, grid, etc). See http://json-schema.org/latest/json-schema-validation.html#anchor104

**Comment by rsuter** [comment]
Maybe you should write a object tree traverser to enhance the model for your needs... All your are extremely customized for your needs and do not really fit into a generic JSON Schema library...

**Comment by AndyEdmonds** [comment]
Hi Rico,
They've moved it to the hyper schema. It's still there as far as I can see on your link.
You are probably right that json-editor is trying to stretch the spec, but it would be nice anyway.

**Comment by rsuter** [comment]
I understand your problem, as I've implemented something similar: http://visualjsoneditor.org. It is important only add really required customizations because you can never remove/or change them later...

**Comment by rsuter** [comment]
Ok, ill add the attributes JsonSchemaFormat and JsonSchemaType to a new nuget NJsonSchema.Annotations. Additionally a IsReadOnly property to the JsonSchema4 class & documentation

**Comment by rsuter** [comment]
... then you can "abuse" the format field ;-)

**Comment by rsuter** [comment]
Ok, features added: 

IsReadOnly: https://github.com/NJsonSchema/NJsonSchema/commit/0cf3a6368b1c89eb5b62543fcbd643419e1f43d9
JsonSchemaAttribute: https://github.com/NJsonSchema/NJsonSchema/commit/e56b0080a54ae9621852dde993a8f57fc1aa1bba

**Comment by rsuter** [comment]
NuGet v1.37 released: https://www.nuget.org/packages/NJsonSchema/1.37.5912.16399

**Comment by rsuter** [comment]
Dokumented here: https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator
