### ISSUE TITLE
TypeMapper proper usage

### ISSUE THREAD

**Issue by Cephei** [NJsonSchema/NJsonSchema#344]
What is the proper way to use `JsonSchemaGenerator` and `JsonSchemaResolver` within a `TypeMapper`? I'm running into so many issues getting my swagger output to be how I want.

I'll try my best to recreate a simplified example:
```
    public class PrincipalGroupDto : CcmpObjectDto
    {
        public IEnumerable<GroupBreadcrumbDto> Breadcrumbs { get; set; }
    }

    public class CcmpObjectDto
    {
        public String Id { get; set; }

        public String Name { get; set; }

        public ObjectTypes ObjectType { get; set; }
    }

    public class GroupBreadcrumbDto
    {
        public IEnumerable<PrincipalGroupDto> Trail { get; set; }
    }
```

1. I want to leverage TypeMappers for pretty much all my objects and define each property
2. I would rather not use `new JsonSchema4()` to create the schema/manually add all properties
3. I don't understand the design of (probably because I'm new to swagger),
> "Definitions"
>> "PrincipalGroupDto"
>>> "Definitions"
>>>> "CcmpObjectDto"
>>>> "GroupBreadcrumbDto"
>>>> "ObjectTypes"

Most of our object inherit from CcmpObjectDto, so therefore have all these nested `definitions`. Furthermore, my `ObjectTypes` `CcmpObjectDto` `GroupBreadcrumbDto` TypeMappers (reference, not primitive) are used but the output does not reflect them.

- Why aren't all types just listed under the root `Definitions` array?

I have TypeMappers registered with each object. The first object to be defined by NSwag Controller/NJsonSchema has an operation parameter of `PrincipalGroupDto`.

I've been doing something like this to try and leverage the TypeMappers:
```
GenerateSchema<TSchemaType>(TSchemaType schema, JsonSchemaGenerator schemaGenerator, JsonSchemaResolver schemaResolver)

var adjustedSettings = Settings.Copy(); // create copy
var typeMapper = adjustedSettings.TypeMappers.SingleOrDefault(m => m.MappedType == MappedType);
if (typeMapper != null)
    adjustedSettings.TypeMappers.Remove(typeMapper); // remove current TypeMapper to avoid loop

return JsonSchema4.FromTypeAsync(MappedType, adjustedSettings); // leverage other TypeMappers for nested properties
```

**Comment by rsuter** [comment]
Inheritance is not described with `definitions`, see http://swagger.io/specification/#models-with-polymorphism-support-91

(definitions are only containers for more Schemas...)

**Comment by Cephei** [comment]
Why would I be getting nested definitions though? I'll try adding a descriminator.

**Comment by rsuter** [comment]
You have to use the `schemaGenerator` to generate schemas (and not `JsonSchema4.FromTypeAsync`) and you dont have to check if there are typemappers (done by the JsonSchemaGenerator)

**Comment by Cephei** [comment]
Thanks for the quick support. I had originally tried that, but ran into a circular problem.

For instance, a type mapper for `PrincipalGroupDto`
`MappedType`=`PrincipalGroupDto`
When I try to use `generator.GenerateAsync(MappedType, resolver);` within my TypeMapper, it just re-enters the TypeMapper.GenerateSchema().

Which kind of makes sense. It's the type mapper for `PrincipalGroupDto`. But I don't want to manually have to create each property. I was hoping to be able to leverage NJsonSchema for that.

So ideally, within my type mapper for PrincipalGroupDto, I can use NJsonSchema to create a JsonSchema4 for PrincipalGroupDto, which creates the properties for me - including nested complex properties (that have their own TypeMappers).

**Comment by rsuter** [comment]
You only have to define a type mapper for types that need to be mapped... if you still want to generate the mapped type (and maybe change the generated schema), we may need to add an additional Parameter `ignoreTypeMappers` to `GenerateAsync`

**Comment by Cephei** [comment]
Yesss!!! Got it working by doing a little trickery:
```
_DefaultSchemaFactory = async (generator, resolver) =>
                {
                    generator.Settings.TypeMappers.Remove(this);
                    var schema = await generator.GenerateAsync(MappedType, resolver);
                    generator.Settings.TypeMappers.Add(this);

                    return schema;
                };
```

Doesn't make much sense without context but I've been playing with a fluent builder syntax for creating documentation.

e.g.
```
public async Task DocumentController(OpenAPIControllerDocumentationBuilder<GroupsController> builder)
        {
            builder.DocumentOperation(HttpMethod.Get, ctlr => ctlr.GetGroup(Arg<string>._))
                .AddResponse(HttpStatusCode.OK, typeof(GroupDto), @"The Group object associated with the specified group identifier.")
                .Parameter(0, @"The identity of the group that is being retrieved.")
                .Summary(@"Returns a Group object associated with the specified group identifier.");

            builder.DocumentOperation(ApiHttpMethod.Patch, ctlr => ctlr.PatchGroups(Arg<string>._, Arg<PatchRequest<PrincipalGroupDto>>._))
                .Parameter(1, (g, r, p) =>
                {
                    p.Name = "principalGroupDto";
                    p.Type = JsonObjectType.Object;
                    p.Schema = new JsonSchema4 { SchemaReference = g.GenerateAsync(typeof(PrincipalGroupDto), r).Result};
                });
        }
```

```
public async Task Define(OpenAPITypeDefinitionBuilder<GroupDto> builder)
        {
            builder
                .For(g => g.Id, p => p.Description = @"The identifier for the group.")
                .For(g => g.Name, p =>
                {
                    p.MinLength = 1;
                    p.MaxLength = 100;
                    p.Description = @"The name of the group you are creating. Must be unique.";
                })
                .For(g => g.JobTitle, p =>
                    {
                        p.MaxLength = 100;
                        p.Description =
                            @"The name of a linked job title. By setting this parameter, any current membership for 
                              this group will be removed and this group’s membership will be linked to any users who 
                              have the given job title. If the job title doesn’t already exist, it will be created.".RemoveMultipleSpaces();

                    }) 
                .For(g => g.Location, p =>
                    {
                        p.MaxLength = 100;
                        p.Description =
                            @"The name of a linked location. By setting this parameter, this group’s membership will 
                              be linked to any users who have this location. A group with the location set may not specify 
                              users as members of the group. If the location doesn’t already exist, it will be created.".RemoveMultipleSpaces();
                    })
                .For(g => g.CallingContext, p => null);
        }
```

**Comment by Cephei** [comment]
All my definitions seem to be working out now. Can't thank you enough for your quick responses!!!

**Comment by Cephei** [comment]
I have some instances in which I prefer not to use a SchemaReference. For instance, on an ApiController SwaggerParameter. In this scenario, is it correct to use a TypeMapper with `UseReference=false` for a TypeMapper associated with the parameter type?

ex.
```
"parameters": [
          {
            "name": "members",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CcmpObjectDto"
              }
            },
            "x-nullable": true,
            "description": "The request body may contain an array of user and/or group objects."
          }
        ]
```

I would like `"items"` to be defined inline so I can customize it.

**Comment by Cephei** [comment]
My apologies for all the re-opens/closes. I've tried to step through and understand the flow of everything before writing. I just realized that the bug I was hunting down was one I already discovered in NSwag. ... unrelated to njsonschema

**Comment by rsuter** [comment]
No problem :)
