### ISSUE TITLE
Error in validate function

### ISSUE THREAD

**Issue by Ladeia** [NJsonSchema/NJsonSchema#354]
I was use this lib in version 5.19.6171.28316, for validate json with jsonschema phisical archieve.
My code is:

`var schema = NJsonSchema.JsonSchema4.FromJson(schemaData);      
var errors = schema.Validate(content);`

 and it is OK, but I update version for newest and change the code for:

`var schema = JsonSchema4.FromData(schemaData);      
 var errors = schema.Validate(content); `

But I receive one error usng the same schema and archieve.

**Comment by rsuter** [comment]
You have to use `FromJsonAsync`, `FromData` creates a schema for the given data, it is not read as schema but as sample data...

**Comment by Ladeia** [comment]
thanks, but when I try

```
var schema = await JsonSchema4.FromJsonAsync(schemaData);
schemaData = schema.ToJson();
var errors = schema.Validate();
```

schema dont have ToJson and Validate methods

**Comment by Ladeia** [comment]
My mistakes, its OK
