### ISSUE TITLE
DateParseHandling.DateTimeOffset leads to exceptions during schema validation.

### ISSUE THREAD

**Issue by rutger-dijkstra** [NJsonSchema/NJsonSchema#38]
When using DateParseHandling.DateTimeOffset (rather than the lossy default DateParseHandling.DateTime) in Newtonsoft.Json, validating the data against an NJsonSchema.JsonSchema4 results in an InvalidCastException in JsonSchemaValidator.ValidateString.

Attached are two patches: one addition to the UnitTests to demonstrate the problem and one very small one to the JsonSchemaValidator that fixes the problem.

[DateTimeOffset-patches.zip](https://github.com/NJsonSchema/NJsonSchema/files/171682/DateTimeOffset-patches.zip)

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/0f82af24ede57d1130d2ec694b9e2aa20199b9de
