### ISSUE TITLE
Extensibility issue

### ISSUE THREAD

**Issue by hamidmoghadam** [NJsonSchema/NJsonSchema#45]
Hey, I would like to know if there is any way to add custom extension data to a property (i.e "sortable : true") to JSchema4 object?

**Comment by rsuter** [comment]
Currently, the only way is to inherit from `JsonSchema4`. However, this way only the root element can have additional properties (properties, etc still are not extensible).

**Comment by rsuter** [comment]
Do you think of a dictionary with additional properties, i.e.: 

    public Dictionary<string, object> AdditionalData { get; }

where the key is the property name and the value any object which is serialized to JSON?

**Comment by hamidmoghadam** [comment]
Yes, exactly.
Like ExtensionData property on JSchema object of Json.Net.Schema library which you can add more metadata to your schema.

**Comment by rsuter** [comment]
Added in commit: https://github.com/NJsonSchema/NJsonSchema/commit/8d817ee224f23a752500df92af0d3746eb0c7fe3

**Comment by rsuter** [comment]
And an attribute for the generator: https://github.com/NJsonSchema/NJsonSchema/commit/57f33cdc6f53730d7a650aeca56b700f5f3d5d57

**Comment by rsuter** [comment]
Ok, NuGet v2.5 is now available...

**Comment by rsuter** [comment]
Please report if everything is working for you

**Comment by dyetube** [comment]
For some reason my `public Dictionary<string, object> values { get; set; }` get's converted to:  

`"values": {
                "type": [
                  "null",
                  "object"
                ],
                "additionalProperties": {
                  "type": "object"
                }
              }`
This causes a validation error.  How can I fix this?

**Comment by rsuter** [comment]
Can you open a new issue? (and post more of the generated JSON Schema?)
