### ISSUE TITLE
consider reading schema from a external file

### ISSUE THREAD

**Issue by vmaramreddy1** [NJsonSchema/NJsonSchema#6]
Hi Rico Suter,

I have gone through the provided Demo and Tests of NJsonSchema.Codegeneration .  I have found only the following two ways -
1.  From JSon data 
2. From C# Type

But are you supporting reading json schema from external file ? If not will you be able to consider this ?

Thanks,
Vijay.

**Comment by rsuter** [comment]
Try 

    JsonSchema4.FromJson(File.ReadAllText(...));

**Comment by vmaramreddy1** [comment]
I though it will just read the plain json text instead of schema .  I will check and get back to you then .
Thanks for your quick help.

**Comment by khairnarnitin** [comment]
Hi Rico Suter,
Somehow this feature is not working for me with the version 1.22.5836.1197. I have created two sample json files stored in C:\Test folder as below.
C:\Test\Person.json
{
    "type": "object",
    "properties": {
        "name": { "type": "string" },
        "addresses": {
            "type": "array",
            "items": { "$ref": "address.json" }
        }
    }
}
C:\Test\address.json
{
    "type": "object",
    "properties": {
        "street": {"type": "string"},
        "city": {"type": "string"}
    }
}
then I have created one sample tests as below.
            var schema = JsonSchema4.FromJson(File.ReadAllText(@"c:\test\person.json"));
            var data = JToken.Parse(File.ReadAllText(@"c:\test\data.json"));
            var errors = schema.Validate(data);
First line throws exception
An unhandled exception of type 'System.NotSupportedException' occurred in NJsonSchema.dll
Additional information: Could not resolve the path 'address.json' because JSON file references are not supported.
Am I doing something wrong?. Please look into it.

**Comment by rsuter** [comment]
I think file references are not supported yet. I have to check the code tomorrow if there's an easy way to do this...

**Comment by khairnarnitin** [comment]
Okay, thanks for quick reply. It will be great help since it is part of Draft 4 Schema specs & we cant have large schema files.

**Comment by rsuter** [comment]
Ok, its fixed now in 1.23, please try again

**Comment by khairnarnitin** [comment]
Thanks. I will try with the latest 1.24 version. Does it supports web references?

**Comment by rsuter** [comment]
No, not yet. But i can add this too...

**Comment by rsuter** [comment]
Do you mean an absolute web references which starts either with "http" or "https"?

**Comment by khairnarnitin** [comment]
Okay thanks for quick reply :).
Yes exactly.

**Comment by khairnarnitin** [comment]
Tried with same sample using 1.24 but it is throwing exception 
Could not resolve the path 'address.json' because no root path is available.

**Comment by rsuter** [comment]
You need to load it using the new method `JsonSchema4.FromFile()`

**Comment by rsuter** [comment]
... otherwise the file path is not known by the parser (as stated by the exception).

**Comment by khairnarnitin** [comment]
Yes... sorry my bad.. tried with FromFile(), it is working.
Cheers!!!

**Comment by rsuter** [comment]
v1.25 now supports now supports URL references...

**Comment by khairnarnitin** [comment]
Thanks it is working.

**Comment by khairnarnitin** [comment]
have you provided any class for n/w proxy settings?

**Comment by rsuter** [comment]
sorry, I don't understand your question?
