### ISSUE TITLE
public List<string> operators { get; set; } is causing validation errors

### ISSUE THREAD

**Issue by dyetube** [NJsonSchema/NJsonSchema#60]
I'm generating a json schema from a class and everything works except: `public Dictionary<string, object> values { get; set; }`.

For some reason it converts it to:

`"values": {
                "type": [
                  "null",
                  "object"
                ],
                "additionalProperties": {
                  "type": "object"
                }
              },`.

What the json should look like is this:

`"values": {
                    "employee Only": "Employee Only",
                    "employee and Spouse": "Employee and Spouse",
                    "employee and Children": "Employee and Children",
                    "employee and Family": "Employee and Family"
                }`

This is causing an error to be thrown when it shouldn't.

If you want me to post the fully convert Json Schema, I can but it is quite long.  Hopefully this makes sense.  I'm thinking the "additionalProperties" is what is causing the error.  Am I doing something wrong maybe?

**Comment by rsuter** [comment]
Looks correct to me, can you post exception details?

**Comment by dyetube** [comment]
It says "ArrayItemNotValid"
![screenshot](https://cloud.githubusercontent.com/assets/7890178/14903967/91e6ffb4-0d6a-11e6-8660-3a99b078e6a3.jpg)
Does this screenshot help or do you need more info?

**Comment by rsuter** [comment]
You have a validation error in the filters property not in the values property... Can you post its data and schema as well?

**Comment by rsuter** [comment]
**Clarification:** JSON Schema does not know dictionaries. The schema describes an object which can have any properties (i.e. the dictionary keys) of type object (i.e. the dictionary values)... Because the property is nullable, its JSON Schema type can be `null` or `object` (as described).

**Comment by dyetube** [comment]
Post the wrong screenshot.  I know I do have an error there, I've got that fixed.  maybe this screenshot will help better?

![screenshot2](https://cloud.githubusercontent.com/assets/7890178/14904213/59d15e6a-0d6c-11e6-980b-e611416255b8.jpg)

![screenshot3](https://cloud.githubusercontent.com/assets/7890178/14904216/5d6cf89a-0d6c-11e6-81fa-f76902e3d43c.jpg)

**Comment by rsuter** [comment]
Ok, I see the problem. Probably `string` is not recognized as JSON Schema `object`...

**Comment by dyetube** [comment]
The reason it can be null or object is that I didn't make it required.  If it is Null, I get no errors, I only get errors when I populate it with key:value pairs as an object.

**Comment by rsuter** [comment]
I have to implement a Unit Test... I'll report back...

**Comment by dyetube** [comment]
Ok.  Thanks!

**Comment by rsuter** [comment]
According to http://jsonschemalint.com/draft4/ the JSON Schema validation is correct for the given data: 

![image](https://cloud.githubusercontent.com/assets/2603405/14904510/ea838622-0da8-11e6-80d7-9babbee9ec41.png)

So we have to change the JSON Schema generator...

**Comment by rsuter** [comment]
I've added the following unit test: 

        public class DictTest
        {
            public Dictionary<string, object> values { get; set; }
        }

        [TestMethod]
        public void When_dictionary_value_is_null_then_string_values_are_allowed()
        {
            //// Arrange
            var schema = JsonSchema4.FromType<DictTest>();
            var schemaData = schema.ToJson();

            var data = @"{
                ""values"": { 
                    ""key"": ""value"", 
                }
            }";

            //// Act
            var errors = schema.Validate(data);

            //// Assert
            Assert.AreEqual(0, errors.Count);
        }

Is this correct?

**Comment by rsuter** [comment]
Commit: https://github.com/NJsonSchema/NJsonSchema/commit/640661879792243bfae92196a17d5beb19945f01

**Comment by rsuter** [comment]
v2.11 now available via NuGet, please try with this version and report if it works...

**Comment by dyetube** [comment]
Sorry it took a while to get back with you on this.  Yes, this fixed the issue and now dictionary works correctly.

**Comment by rsuter** [comment]
Nice. Thx for reporting the issue and using the library...
