### ISSUE TITLE
Filed not letting me have null and expects an object.

### ISSUE THREAD

**Issue by dyetube** [NJsonSchema/NJsonSchema#62]
Whenever I use something like:

`public QueryRule ReportRules { get; set; }` or `public Validation validation { get; set; }`

it won't let it be null, it errors out expecting an object even though I've not set it to required and I need to be able to let the value be null and not have to put an empty object in it's place.  have you encountered this before as well?

**Comment by rsuter** [comment]
Can you post the JSON Schema?

This test works for me: 

    [TestMethod]
    public void When_property_can_be_null_then_null_is_allowed()
    {
        //// Arrange
        var schema = new JsonSchema4();
        schema.Properties["test"] = new JsonProperty
        {
            Type = JsonObjectType.Null | JsonObjectType.Object
        };
        schema.Properties["test"].Properties["foo"] = new JsonProperty
        {
            Type = JsonObjectType.String
        };

        //// Act
        var data = "{ 'test': null }";
        var errors = schema.Validate(data);

        //// Assert
        Assert.AreEqual(0, errors.Count);
    }

**Comment by dyetube** [comment]
`"validation": {
                "type": [
                  "null",
                  "object"
                ],
                "$ref": "#/definitions/Validation"
              },`

For `public Validation validation { get; set; }` and:

` "ReportRules": {
      "type": [
        "null",
        "object"
      ],
      "$ref": "#/definitions/QueryRule"
    },`

for `public QueryRule ReportRules { get; set; }.`

**Comment by dyetube** [comment]
Any clues?

**Comment by rsuter** [comment]
This is a bad one, there is a problem with properties and schema refs.. I have to fix this but it will take a while...

**Comment by rsuter** [comment]
Should be fixed in: https://github.com/NJsonSchema/NJsonSchema/commit/aa559b788a511fc74e7b913e679f04697b3c7f8a
I have to do more tests with these changes...

**Comment by rsuter** [comment]
Fixed in NSwag v2.13
