### ISSUE TITLE
Getting Too Many Properties In Tuple error.

### ISSUE THREAD

**Issue by dyetube** [NJsonSchema/NJsonSchema#68]
When validating the Json schema against an mvc model, it get the error 'Too Many Properties In Tuple" and the path and property get set to null which errors out my code with "Cannot perform runtime binding on a null reference".  Amy ideas on what causes this?

**Comment by rsuter** [comment]
Can you provide a sample schema and sample data?

**Comment by dyetube** [comment]
You want me to include the models?  I don't have the actual Schema, I use `var schema = JsonSchema4.FromType<ReportItem>();` and `var schemaData = schema.ToJson();` to build the schema from my models and then `var errors = schema.Validate(JSend.JsonString);` to get the errors.

**Comment by rsuter** [comment]
Can you post the schemaData and JSend.JsonString content here (or is it confidential)?

**Comment by dyetube** [comment]
here ya go:

`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "typeName": "ReportItem",
  "additionalProperties": false,
  "required": [
    "ReportID",
    "RequiresFilter",
    "MimeType",
    "ExternalID",
    "CreatedBy",
    "ExecutionScript",
    "ExecutionParameter",
    "Columns"
  ],
  "properties": {
    "ReportID": {
      "type": "string",
      "format": "guid"
    },
    "RequiresFilter": {
      "type": "boolean"
    },
    "MimeType": {
      "type": "string"
    },
    "ExternalID": {
      "type": "string"
    },
    "CreatedBy": {
      "type": "string",
      "format": "date-time"
    },
    "ExecutionScript": {
      "type": "string"
    },
    "ExecutionParameter": {
      "type": "string"
    },
    "ExecutionOrderBy": {
      "type": [
        "null",
        "string"
      ]
    },
    "DynamicFilters": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "typeName": "DynamicFilter",
        "additionalProperties": false,
        "required": [
          "ID",
          "Script",
          "ScriptOrderBy",
          "Fields",
          "ScriptParams"
        ],
        "properties": {
          "ID": {
            "type": "string"
          },
          "Script": {
            "type": "string"
          },
          "ScriptOrderBy": {
            "type": "string"
          },
          "Fields": {
            "type": "string"
          },
          "ScriptParams": {
            "type": "object",
            "additionalProperties": {
              "type": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string"
              ]
            }
          }
        }
      }
    },
    "RequiresOrgID": {
      "type": "boolean"
    },
    "ReportFilter": {
      "oneOf": [
        {
          "$ref": "#/definitions/QueryFilter"
        },
        {
          "type": "null"
        }
      ]
    },
    "ReportRules": {
      "oneOf": [
        {
          "$ref": "#/definitions/QueryRule"
        },
        {
          "type": "null"
        }
      ]
    },
    "Columns": {
      "type": "array",
      "items": {
        "type": "object",
        "typeName": "QueryColumn",
        "additionalProperties": false,
        "required": [
          "isrequired",
          "column_name"
        ],
        "properties": {
          "isrequired": {
            "type": "boolean"
          },
          "column_name": {
            "type": "string"
          }
        }
      }
    }
  },
  "definitions": {
    "QueryFilter": {
      "type": "object",
      "typeName": "QueryFilter",
      "additionalProperties": false,
      "required": [
        "display_errors",
        "allow_empty",
        "plugins",
        "filters"
      ],
      "properties": {
        "display_errors": {
          "type": "boolean"
        },
        "allow_empty": {
          "type": "boolean"
        },
        "plugins": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "filters": {
          "type": "array",
          "items": {
            "type": "object",
            "typeName": "Filter",
            "additionalProperties": false,
            "required": [
              "id",
              "label",
              "type",
              "operators"
            ],
            "properties": {
              "id": {
                "type": "string"
              },
              "label": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "operators": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "input": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "values": {
                "type": [
                  "null",
                  "object"
                ],
                "additionalProperties": {
                  "type": [
                    "array",
                    "boolean",
                    "integer",
                    "null",
                    "number",
                    "object",
                    "string"
                  ]
                }
              },
              "validation": {
                "oneOf": [
                  {
                    "$ref": "#/definitions/Validation"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "unique": {
                "type": "boolean"
              },
              "description": {
                "type": [
                  "null",
                  "string"
                ]
              }
            }
          }
        }
      }
    },
    "QueryRule": {
      "type": "object",
      "typeName": "QueryRule",
      "additionalProperties": false,
      "properties": {
        "condition": {
          "type": [
            "null",
            "string"
          ]
        },
        "rules": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "object",
            "typeName": "Rule",
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "operator": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "value": {
                "type": [
                  "null",
                  "object"
                ]
              },
              "readonly": {
                "type": "boolean"
              },
              "condition": {
                "type": [
                  "null",
                  "string"
                ]
              }
            }
          }
        }
      }
    },
    "Validation": {
      "type": "object",
      "typeName": "Validation",
      "additionalProperties": false,
      "properties": {
        "min": {
          "type": "integer"
        },
        "step": {
          "type": "number",
          "format": "double"
        }
      }
    }
  }
}
`

**Comment by dyetube** [comment]
If I use something simple like  {"Key": "Value"} as the json to compare this schema against, that's when I get the error.  I'm doing a workaround, but would rather have this work properly if possible.

**Comment by rsuter** [comment]
Do you also have sample data?

**Comment by rsuter** [comment]
Ok, ill check this asap

**Comment by dyetube** [comment]
Sweet.  Thanks again!

**Comment by rsuter** [comment]
The validation is correct, the error is not a property but an object error and the path is null because it applies to the root object. I added a unit test for your case and appended `#` to the error `Path`. This way all paths start with `#` (= root) and this error on the root object has `#` in the `Path` property...

https://github.com/NJsonSchema/NJsonSchema/commit/efd8a8ddb3d1907accdee0cd54bfb69512159ed3

**Comment by rsuter** [comment]
Do you expect something else?

**Comment by dyetube** [comment]
Wasn't thinking about the fact that it's an object and therefore has no path.  What I am doing actually works just fine.  Thanks for the help.

**Comment by rsuter** [comment]
In the next version, each path will start with # (same as in a JSON ref) it will never be null.. Is this a problem for you?

**Comment by dyetube** [comment]
This shouldn't be a problem.  I'm iterating through the errors and adding them to an array using an `Results.Add(new JsonReportErrors { ErrorKind = error.Kind.ToString(), ErrorPath = error.Path.ToString() });` statement and that was erroring out because of the null.  Now that it will have a # and not be null, I'll be good.
