### ISSUE TITLE
Support deriving top level type name from json schema id

### ISSUE THREAD

**Issue by lheiskan** [NJsonSchema/NJsonSchema#89]
It would be nice if top level type name could be derived from the schema id - this would allow code generation from schemas without adding typeName fields.

For instance, if schema id is "http://domain.name.com/foo.json#" then type name for the top level type would become 'foo' (instead of Anonymous).

**Comment by rsuter** [comment]
Good idea as fallback if typeName is missing..

**Comment by rsuter** [comment]
Can now be implemented using ITypeNameGenerator, see https://github.com/NJsonSchema/NJsonSchema/issues/96
