### ISSUE TITLE
Document supported attributes

### ISSUE THREAD

**Issue by acelot** [NJsonSchema/NJsonSchema#9]
```cs
public class Model
{
    [JsonProperty("key")]
    [Display(Description = "Some description")]
    public int Key { get; set; }
    
    [JsonProperty("value")]
    public string Value { get; set; }
}
```

```cs
var schema = JsonSchema4.FromType<Model>();
Console.WriteLine(schema.ToJson());
```

```json
{
  "typeName": "Model",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "key"
  ],
  "properties": {
    "key": {
      "type": "integer"
    },
    "value": {
      "type": "string"
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by rsuter** [comment]
For now, you can use the `DescriptionAttribute` (`System.ComponentModel.DescriptionAttribute`)... But I will add support for the `DisplayAttribute` soon

**Comment by acelot** [comment]
@rsuter thanks! Can you please enlist all supported data attributes in README?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator

**Comment by acelot** [comment]
@rsuter, great! How about array size restricting? `minItems`, `maxItems`?

**Comment by rsuter** [comment]
There's currently no way to express this... is there an existing attribute we can use?

**Comment by acelot** [comment]
https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.minlengthattribute(v=vs.110).aspx

**Comment by acelot** [comment]
Also I can't find the `title` attribute. It would be handy set the `title` and `description` attributes through `Display`. For example:

```cs
[JsonProperty("id")]
[Display(Name="ID", Description="User ID")]
public int Id { get; set; }
```

**Comment by rsuter** [comment]
Is this as expected?
https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema.Tests/Generation/AttributeGenerationTests.cs

**Comment by acelot** [comment]
@rsuter, awesome!

**Comment by rsuter** [comment]
is it correct this way? then i'll publish the nuget package...

**Comment by acelot** [comment]
@rsuter, yes, I approve!

**Comment by rsuter** [comment]
Done. v1.20

**Comment by rsuter** [comment]
Unit tests, new features and documentation updated
