### ISSUE TITLE
Support customizing the generated property and type names

### ISSUE THREAD

**Issue by lheiskan** [NJsonSchema/NJsonSchema#96]
It would be nice if there was a way to (optionally) customize the names for generated properties and types. For instance, we could add few optional generator settings that would allow passing in lambdas for customizing the naming. Lambdas would receive the type|property name from json schema as input, and return the name to use in the generated code. Something like this:
 ```csharp
            Func<string, string> namingTransform = (name) => {
                // some_name-b64  ==> SomeName_b64
                var components = name.Split('_');
                var transformedComponents =  components
                        .Select((c) => c.First().ToString().ToUpperInvariant() + c.Substring(1))
                        .Select((c) => c.Replace("-", "_"));
                return string.Join("", transformedComponents);
            };
            var settings = new CSharpGeneratorSettings() {
                    ClassStyle = CSharpClassStyle.Poco,
                    PropertyNameFun = namingTransform, 
                    TypeNameTransformFun = namingTransform 
            };
```
So given schema
```json
	    {
                '$schema': 'http://json-schema.org/draft-04/schema#',
                'id': 'http://domain.name.com/foo.json#',
                'type': 'object',
                'additionalProperties': false,
                'properties': {
                    'foo_bar-b64': {
                        'type': 'string'
                     }
                }
	     }
```	
Generated code would end up looking something like this
```csharp	
	public class Foo {
		public string FooBar_b64 {get;set;}
	}
```

**Comment by rsuter** [comment]
It would be better if its static settings so that it can also be used in the cmd line tool or UI... Or give both options.

**Comment by rsuter** [comment]
Btw. whats currently the name of this property?

**Comment by lheiskan** [comment]
Static alternatives should become easy to implement if the library has a mechanism like this in place, so perhaps supporting both would make sense?

Not sure which property you are referring to?

**Comment by lheiskan** [comment]
i.e. the above has a schema with a property 'foo_bar-b64', generator settings has been extended with two additional properties: PropertyName(Transform)Fun and TypeNameTransformFun.

**Comment by rsuter** [comment]
Good idea...

**Comment by rsuter** [comment]
Ill check how to correctly implement this...

**Comment by lheiskan** [comment]
I've hacked something in for generating CS, if you are interested i can clean things up a bit and put it in a branch - i.e. if it helps, let me know.

**Comment by rsuter** [comment]
You can create a PR so that I can check it, but we have to be very careful to not break anything and keep the code quality high... I probably will implement this myself because i know all the dependencies and strange specialities of JSON Schema and this lib.

**Comment by rsuter** [comment]
The lib is also used in http://NSwag.org and all changes have to be aligned with that (+ options added to cmd line tools, desktop UI, etc). There's always more effort involved :-)

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/908c364e4e5c8144fba2d77acb9486d83f273660

**Comment by rsuter** [comment]
ITypeNameGenerator: https://github.com/NJsonSchema/NJsonSchema/commit/d95ca7751d534cd822da4f54fce3431d845481cb

**Comment by rsuter** [comment]
These features are currently not tested (ie everything works as expected when they are null). It would be very nice if you can add some unit tests to test the `PropertyNameGenerator` and `TypeNameGenerator`!
